"""Model locking submissions to prevent simultaneous edits

Revision ID: 0f87ba7add08
Revises: de3d2eaa2a59
Create Date: 2023-11-28 21:44:38.913030

"""
from typing import Optional

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0f87ba7add08"
down_revision: Optional[str] = "de3d2eaa2a59"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("submission_metadata", sa.Column("lock_updated", sa.DateTime(), nullable=True))
    op.add_column(
        "submission_metadata",
        sa.Column("locked_by_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_submission_metadata_locked_by_id_user_logins"),
        "submission_metadata",
        "user_logins",
        ["locked_by_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("submission_metadata", "locked_by_id")
    op.drop_column("submission_metadata", "lock_updated")
    op.drop_constraint(op.f("uq_envo_ancestor_id"), "envo_ancestor", type_="unique")
    # ### end Alembic commands ###
