"""Add column to study relation for MASSive identifiers

Revision ID: 11a7decdcc60
Revises: b96ecfffa792
Create Date: 2023-03-20 19:54:08.406526

"""

from typing import Optional

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "11a7decdcc60"
down_revision: Optional[str] = "b96ecfffa792"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "study",
        sa.Column(
            "massive_study_identifiers",
            postgresql.JSONB(astext_type=sa.Text()),  # type: ignore
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("study", "massive_study_identifiers")
    # ### end Alembic commands ###
