"""Add qc info fields to PipelineStep

Revision ID: 133e1dbe1d42
Revises: c13f3b9b0e4d
Create Date: 2026-10-01 21:24:59.741234

"""

from typing import Optional

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "133e1dbe1d42"
down_revision: Optional[str] = "c13f3b9b0e4d"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mags_analysis", sa.Column("qc_status", sa.String(), nullable=True))
    op.add_column("mags_analysis", sa.Column("qc_comment", sa.String(), nullable=True))
    op.add_column("mags_analysis", sa.Column("has_failure_categorization", postgresql.JSONB(astext_type=sa.Text()), nullable=True))  # type: ignore
    op.add_column("metabolomics_analysis", sa.Column("qc_status", sa.String(), nullable=True))
    op.add_column("metabolomics_analysis", sa.Column("qc_comment", sa.String(), nullable=True))
    op.add_column("metabolomics_analysis", sa.Column("has_failure_categorization", postgresql.JSONB(astext_type=sa.Text()), nullable=True))  # type: ignore
    op.add_column("metagenome_annotation", sa.Column("qc_status", sa.String(), nullable=True))
    op.add_column("metagenome_annotation", sa.Column("qc_comment", sa.String(), nullable=True))
    op.add_column("metagenome_annotation", sa.Column("has_failure_categorization", postgresql.JSONB(astext_type=sa.Text()), nullable=True))  # type: ignore
    op.add_column("metagenome_assembly", sa.Column("qc_status", sa.String(), nullable=True))
    op.add_column("metagenome_assembly", sa.Column("qc_comment", sa.String(), nullable=True))
    op.add_column("metagenome_assembly", sa.Column("has_failure_categorization", postgresql.JSONB(astext_type=sa.Text()), nullable=True))  # type: ignore
    op.add_column("metaproteomic_analysis", sa.Column("qc_status", sa.String(), nullable=True))
    op.add_column("metaproteomic_analysis", sa.Column("qc_comment", sa.String(), nullable=True))
    op.add_column("metaproteomic_analysis", sa.Column("has_failure_categorization", postgresql.JSONB(astext_type=sa.Text()), nullable=True))  # type: ignore
    op.add_column("metatranscriptome", sa.Column("qc_status", sa.String(), nullable=True))
    op.add_column("metatranscriptome", sa.Column("qc_comment", sa.String(), nullable=True))
    op.add_column("metatranscriptome", sa.Column("has_failure_categorization", postgresql.JSONB(astext_type=sa.Text()), nullable=True))  # type: ignore
    op.add_column(
        "metatranscriptome_annotation", sa.Column("qc_status", sa.String(), nullable=True)
    )
    op.add_column(
        "metatranscriptome_annotation", sa.Column("qc_comment", sa.String(), nullable=True)
    )
    op.add_column("metatranscriptome_annotation", sa.Column("has_failure_categorization", postgresql.JSONB(astext_type=sa.Text()), nullable=True))  # type: ignore
    op.add_column("metatranscriptome_assembly", sa.Column("qc_status", sa.String(), nullable=True))
    op.add_column("metatranscriptome_assembly", sa.Column("qc_comment", sa.String(), nullable=True))
    op.add_column("metatranscriptome_assembly", sa.Column("has_failure_categorization", postgresql.JSONB(astext_type=sa.Text()), nullable=True))  # type: ignore
    op.add_column("nom_analysis", sa.Column("qc_status", sa.String(), nullable=True))
    op.add_column("nom_analysis", sa.Column("qc_comment", sa.String(), nullable=True))
    op.add_column("nom_analysis", sa.Column("has_failure_categorization", postgresql.JSONB(astext_type=sa.Text()), nullable=True))  # type: ignore
    op.add_column("read_based_analysis", sa.Column("qc_status", sa.String(), nullable=True))
    op.add_column("read_based_analysis", sa.Column("qc_comment", sa.String(), nullable=True))
    op.add_column("read_based_analysis", sa.Column("has_failure_categorization", postgresql.JSONB(astext_type=sa.Text()), nullable=True))  # type: ignore
    op.add_column("reads_qc", sa.Column("qc_status", sa.String(), nullable=True))
    op.add_column("reads_qc", sa.Column("qc_comment", sa.String(), nullable=True))
    op.add_column("reads_qc", sa.Column("has_failure_categorization", postgresql.JSONB(astext_type=sa.Text()), nullable=True))  # type: ignore
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reads_qc", "has_failure_categorization")
    op.drop_column("reads_qc", "qc_comment")
    op.drop_column("reads_qc", "qc_status")
    op.drop_column("read_based_analysis", "has_failure_categorization")
    op.drop_column("read_based_analysis", "qc_comment")
    op.drop_column("read_based_analysis", "qc_status")
    op.drop_column("nom_analysis", "has_failure_categorization")
    op.drop_column("nom_analysis", "qc_comment")
    op.drop_column("nom_analysis", "qc_status")
    op.drop_column("metatranscriptome_assembly", "has_failure_categorization")
    op.drop_column("metatranscriptome_assembly", "qc_comment")
    op.drop_column("metatranscriptome_assembly", "qc_status")
    op.drop_column("metatranscriptome_annotation", "has_failure_categorization")
    op.drop_column("metatranscriptome_annotation", "qc_comment")
    op.drop_column("metatranscriptome_annotation", "qc_status")
    op.drop_column("metatranscriptome", "has_failure_categorization")
    op.drop_column("metatranscriptome", "qc_comment")
    op.drop_column("metatranscriptome", "qc_status")
    op.drop_column("metaproteomic_analysis", "has_failure_categorization")
    op.drop_column("metaproteomic_analysis", "qc_comment")
    op.drop_column("metaproteomic_analysis", "qc_status")
    op.drop_column("metagenome_assembly", "has_failure_categorization")
    op.drop_column("metagenome_assembly", "qc_comment")
    op.drop_column("metagenome_assembly", "qc_status")
    op.drop_column("metagenome_annotation", "has_failure_categorization")
    op.drop_column("metagenome_annotation", "qc_comment")
    op.drop_column("metagenome_annotation", "qc_status")
    op.drop_column("metabolomics_analysis", "has_failure_categorization")
    op.drop_column("metabolomics_analysis", "qc_comment")
    op.drop_column("metabolomics_analysis", "qc_status")
    op.drop_column("mags_analysis", "has_failure_categorization")
    op.drop_column("mags_analysis", "qc_comment")
    op.drop_column("mags_analysis", "qc_status")
    # ### end Alembic commands ###
