"""empty message

Revision ID: 1d0cfa3cb7b5
Revises: ae7a3eba08c5
Create Date: 2023-01-02 18:13:56.489110

"""
from typing import Optional

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1d0cfa3cb7b5"
down_revision: Optional[str] = "ae7a3eba08c5"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ingest_lock")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingest_lock",
        sa.Column("id", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("started", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.CheckConstraint("id", name="ck_ingest_lock_singleton"),
        sa.PrimaryKeyConstraint("id", name="pk_ingest_lock"),
    )
    # ### end Alembic commands ###
