"""empty message

Revision ID: 20e30659b752
Revises: 7178fbceab2a
Create Date: 2021-08-27 14:50:40.302112

"""
from typing import Optional

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20e30659b752"
down_revision: Optional[str] = "7178fbceab2a"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("search_index", sa.Column("count", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("search_index", "count")
    # ### end Alembic commands ###
