"""Add PFAM to GO mappings

Revision ID: 224d48e7ebe9
Revises: 4aee1e10bb24
Create Date: 2024-11-11 21:45:37.459451

"""

from typing import Optional

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "224d48e7ebe9"
down_revision: Optional[str] = "4aee1e10bb24"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "go_term_text",
        sa.Column("term", sa.String(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("term", name=op.f("pk_go_term_text")),
    )
    op.create_table(
        "go_term_to_pfam_entry",
        sa.Column("term", sa.String(), nullable=False),
        sa.Column("entry", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("term", "entry", name=op.f("pk_go_term_to_pfam_entry")),
    )
    op.create_index(
        op.f("ix_go_term_to_pfam_entry_entry"), "go_term_to_pfam_entry", ["entry"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_go_term_to_pfam_entry_entry"), table_name="go_term_to_pfam_entry")
    op.drop_table("go_term_to_pfam_entry")
    op.drop_table("go_term_text")
    # ### end Alembic commands ###
