"""Remove `used` and `best_protein` columns

Revision ID: 3a68ea418acf
Revises: 9e6c9a57b893
Create Date: 2025-05-13 00:43:32.174705

"""

from typing import Optional

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a68ea418acf"
down_revision: Optional[str] = "9e6c9a57b893"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metabolomics_analysis", "used")
    op.drop_column("metap_gene_function_aggregation", "best_protein")
    op.drop_column("nom_analysis", "used")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "nom_analysis",
        sa.Column("used", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "metap_gene_function_aggregation",
        sa.Column("best_protein", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "metabolomics_analysis",
        sa.Column("used", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
