"""Add include_older_workflow_executions column to bulk_download table

Revision ID: 3b9e6e16c449
Revises: a67ca461ab87
Create Date: 2026-08-07 14:35:42.615273

"""
from typing import Optional

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b9e6e16c449'
down_revision: Optional[str] = 'a67ca461ab87'
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulk_download', sa.Column('include_older_workflow_executions', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bulk_download', 'include_older_workflow_executions')
    # ### end Alembic commands ###
