"""empty message

Revision ID: 3dce13053a91
Revises: ae7a3eba08c5
Create Date: 2022-10-21 16:45:37.166885

"""
from typing import Optional

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dce13053a91'
down_revision: Optional[str] = 'ae7a3eba08c5'
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mag', sa.Column('num_t_rna', sa.BigInteger(), nullable=True))
    op.drop_column('mag', 'num_trna')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mag', sa.Column('num_trna', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('mag', 'num_t_rna')
    # ### end Alembic commands ###
