"""Add generic ontology tables

Revision ID: 43ce041c88cb
Revises: 23ef8096759e
Create Date: 2026-01-21 01:33:58.970768

"""
from typing import Optional

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43ce041c88cb'
down_revision: Optional[str] = '23ef8096759e'
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ontology_class',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('alternative_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_root', sa.Boolean(), nullable=False),
    sa.Column('is_obsolete', sa.Boolean(), nullable=False),
    sa.Column('annotations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_class'))
    )
    op.create_index(op.f('ix_ontology_class_name'), 'ontology_class', ['name'], unique=False)
    op.create_table('ontology_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('predicate', sa.String(), nullable=False),
    sa.Column('object', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['subject'], ['ontology_class.id'], name=op.f('fk_ontology_relation_subject_ontology_class')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_relation')),
    sa.UniqueConstraint('subject', 'predicate', 'object', name=op.f('uq_ontology_relation_subject'))
    )
    op.create_index('idx_ontology_relation_object', 'ontology_relation', ['object'], unique=False)
    op.create_index('idx_ontology_relation_predicate', 'ontology_relation', ['predicate'], unique=False)
    op.create_index('idx_ontology_relation_subject', 'ontology_relation', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ontology_relation_subject', table_name='ontology_relation')
    op.drop_index('idx_ontology_relation_predicate', table_name='ontology_relation')
    op.drop_index('idx_ontology_relation_object', table_name='ontology_relation')
    op.drop_table('ontology_relation')
    op.drop_index(op.f('ix_ontology_class_name'), table_name='ontology_class')
    op.drop_table('ontology_class')
    # ### end Alembic commands ###
