"""Make execution_resource nullable.

Revision ID: 43fc92514a16
Revises: 09a705b0bc00
Create Date: 2025-08-12 18:10:18.144086

"""

from typing import Optional

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43fc92514a16"
down_revision: Optional[str] = "09a705b0bc00"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "mags_analysis", "execution_resource", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "metabolomics_analysis", "execution_resource", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "metagenome_annotation", "execution_resource", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "metagenome_assembly", "execution_resource", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "metaproteomic_analysis", "execution_resource", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "metatranscriptome", "execution_resource", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "metatranscriptome_annotation",
        "execution_resource",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "metatranscriptome_assembly",
        "execution_resource",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column("nom_analysis", "execution_resource", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "read_based_analysis", "execution_resource", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("reads_qc", "execution_resource", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("reads_qc", "execution_resource", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "read_based_analysis", "execution_resource", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "nom_analysis", "execution_resource", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "metatranscriptome_assembly",
        "execution_resource",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "metatranscriptome_annotation",
        "execution_resource",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "metatranscriptome", "execution_resource", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "metaproteomic_analysis", "execution_resource", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "metagenome_assembly", "execution_resource", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "metagenome_annotation", "execution_resource", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "metabolomics_analysis", "execution_resource", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "mags_analysis", "execution_resource", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
