"""empty message

Revision ID: 4b2d6ee63752
Revises: 605ae36be6b5
Create Date: 2025-01-03 18:07:09.029643

"""
from typing import Optional

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2d6ee63752'
down_revision: Optional[str] = '605ae36be6b5'
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_metadata', sa.Column('isTestSubmission', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_metadata', 'isTestSubmission')
    # ### end Alembic commands ###
