"""Add badges to biosample

Revision ID: 514cc831aa3b
Revises: c4a3c1a90a62
Create Date: 2026-09-09 23:26:07.006692

"""
from typing import Optional

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '514cc831aa3b'
down_revision: Optional[str] = 'c4a3c1a90a62'
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biosample', sa.Column('badges', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('biosample', 'badges')
    # ### end Alembic commands ###
