"""Migrate Study names

Revision ID: 5403c7fe0b33
Revises: 0ff690fb929d
Create Date: 2024-09-09 18:50:11.771035

"""

from typing import Optional

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.sql import column, table

# revision identifiers, used by Alembic.
revision: str = "5403c7fe0b33"
down_revision: Optional[str] = "0ff690fb929d"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    submission_metadata = table(
        "submission_metadata",
        column("id", sa.String),
        column("metadata_submission", JSONB),
        column("study_name", sa.String),
    )

    connection = op.get_bind()
    submissions = connection.execute(
        sa.select(submission_metadata.c.id, submission_metadata.c.metadata_submission)
    )

    for submission in submissions:
        study_name = submission.metadata_submission["studyForm"].get("studyName")
        if study_name:
            connection.execute(
                submission_metadata.update()
                .where(submission_metadata.c.id == submission.id)
                .values(study_name=study_name)
            )
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
