"""Add PFAM mappings

Revision ID: 5fb9910ca8e6
Revises: ff4e651c3007
Create Date: 2024-08-30 21:12:14.993046

"""

from typing import Optional

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5fb9910ca8e6"
down_revision: Optional[str] = "ff4e651c3007"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pfam_entry_to_clan",
        sa.Column("entry", sa.String(), nullable=False),
        sa.Column("clan", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("entry", "clan", name=op.f("pk_pfam_entry_to_clan")),
    )
    op.create_index(
        op.f("ix_pfam_entry_to_clan_clan"), "pfam_entry_to_clan", ["clan"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pfam_entry_to_clan_clan"), table_name="pfam_entry_to_clan")
    op.drop_table("pfam_entry_to_clan")
    # ### end Alembic commands ###
