"""Allow null values for certain columns on Reads QC Analyses

Revision ID: 60b8a4b0c60e
Revises: b51ae399d49f
Create Date: 2023-03-28 20:38:56.658391

"""
from typing import Optional

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60b8a4b0c60e"
down_revision: Optional[str] = "b51ae399d49f"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("reads_qc", "input_read_bases", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("reads_qc", "input_read_count", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("reads_qc", "output_read_bases", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("reads_qc", "output_read_count", existing_type=sa.BIGINT(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("reads_qc", "output_read_count", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("reads_qc", "output_read_bases", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("reads_qc", "input_read_count", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("reads_qc", "input_read_bases", existing_type=sa.BIGINT(), nullable=False)
    # ### end Alembic commands ###
