"""index-study-id

Revision ID: 613956d85ada
Revises: b4b234bd55cf
Create Date: 2024-04-11 19:33:18.337288

"""

from typing import Optional

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "613956d85ada"
down_revision: Optional[str] = "b4b234bd55cf"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_biosample_id"), "biosample", ["id"], unique=False)
    op.create_index(op.f("ix_biosample_study_id"), "biosample", ["study_id"], unique=False)
    op.create_index(op.f("ix_omics_processing_id"), "omics_processing", ["id"], unique=False)
    op.create_index(
        op.f("ix_omics_processing_study_id"), "omics_processing", ["study_id"], unique=False
    )
    op.create_index(op.f("ix_study_id"), "study", ["id"], unique=False)
    op.create_unique_constraint(
        op.f("uq_submission_role_submission_id"), "submission_role", ["submission_id", "user_orcid"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_submission_role_submission_id"), "submission_role", type_="unique")
    op.drop_index(op.f("ix_study_id"), table_name="study")
    op.drop_index(op.f("ix_omics_processing_study_id"), table_name="omics_processing")
    op.drop_index(op.f("ix_omics_processing_id"), table_name="omics_processing")
    op.drop_index(op.f("ix_biosample_study_id"), table_name="biosample")
    op.drop_index(op.f("ix_biosample_id"), table_name="biosample")
    # ### end Alembic commands ###
