"""Create `biosample_related_document` table

Revision ID: 6867009bb496
Revises: c5852f4f16b1
Create Date: 2026-02-26 08:56:09.654967

"""

from typing import Optional

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6867009bb496"
down_revision: Optional[str] = "c5852f4f16b1"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # TODO: Consider using a many-to-many association table instead of storing `biosample_id` here.
    #       That way, when a document is related to multiple biosamples, we only have to store
    #       a single copy of that document (as opposed to one copy per biosample).
    op.create_table(
        "biosample_related_document",
        # Note: The `server_default=sa.text("gen_random_uuid()")` will make it so developers can use
        #       a SQL client (such as DBeaver) to create a row that _lacks_ an `id` value, and
        #       Postgres will _automatically_ generate one. This can save developers from having to
        #       context switch.
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "biosample_id", sa.String(), nullable=False, comment="The ID of the subject biosample"
        ),
        sa.Column(
            "document",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="NMDC Schema-compliant document downstream of the subject biosample",
        ),
        sa.ForeignKeyConstraint(
            ["biosample_id"],
            ["biosample.id"],
            name=op.f("fk_biosample_related_document_biosample_id_biosample"),
            ondelete="CASCADE",
        ),
    )
    # Create an index on the "biosample_id" column in an attempt to speed up searches by its values.
    op.create_index(
        index_name="ix_biosample_related_document_biosample_id",
        table_name="biosample_related_document",
        columns=["biosample_id"],
    )
    # Create an index on the "id" JSON field in an attempt to speed up searches by its values.
    op.create_index(
        index_name="ix_biosample_related_document_document_id",
        table_name="biosample_related_document",
        columns=[sa.text("(document->>'id')")],
    )
    # Create an index on the "type" JSON field in an attempt to speed up searches by its values.
    op.create_index(
        index_name="ix_biosample_related_document_document_type",
        table_name="biosample_related_document",
        columns=[sa.text("(document->>'type')")],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        index_name="ix_biosample_related_document_biosample_id",
        table_name="biosample_related_document",
    )
    op.drop_index(
        index_name="ix_biosample_related_document_document_type",
        table_name="biosample_related_document",
    )
    op.drop_index(
        index_name="ix_biosample_related_document_document_id",
        table_name="biosample_related_document",
    )
    op.drop_table("biosample_related_document")
    # ### end Alembic commands ###
