"""Create `biosample_derived_documents` table

Revision ID: 6867009bb496
Revises: c5852f4f16b1
Create Date: 2026-02-26 08:56:09.654967

"""
from typing import Optional

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "6867009bb496"
down_revision: Optional[str] = "c5852f4f16b1"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "biosample_derived_documents",
        # Note: The `server_default=sa.text("gen_random_uuid()")` will make it so developers can use
        #       a SQL client (such as DBeaver) to create a row that _lacks_ an `id` value, and
        #       Postgres will _automatically_ generate one. This can save developers from having to
        #       context switch.
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
            primary_key=True,
            server_default=sa.text("gen_random_uuid()")
        ),
        sa.Column(
            "biosample_id", sa.String(), nullable=False, comment="The ID of the subject biosample"
        ),
        sa.Column(
            "document",
            sa.JSON(),
            nullable=False,
            comment="NMDC Schema-compliant document downstream of the subject biosample"
        ),
        sa.ForeignKeyConstraint(
            ["biosample_id"],
            ["biosample.id"],
            name=op.f("fk_biosample_derived_documents_biosample_id_biosample"),
            ondelete="CASCADE",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("biosample_derived_documents")
    # ### end Alembic commands ###
