"""empty message

Revision ID: 68c2c008f4cf
Revises: 9c4a29f70256
Create Date: 2022-02-01 19:54:38.074549

"""
from typing import Optional

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "68c2c008f4cf"
down_revision: Optional[str] = "9c4a29f70256"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "submission_metadata",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("author_orcid", sa.String(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column(
            "metadata_submission",
            postgresql.JSONB(astext_type=sa.Text()),  # type: ignore
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submission_metadata")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("submission_metadata")
    # ### end Alembic commands ###
