"""

Adds date_last_modified to MetadataSubmission

Revision ID: 6e6dec0daa7c
Revises: 18127fd43a8b
Create Date: 2025-02-03 18:58:55.592754

"""

from typing import Optional

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e6dec0daa7c"
down_revision: Optional[str] = "18127fd43a8b"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the date_last_modified column. Allow it to be null for now while we populate it.
    op.add_column("submission_metadata", sa.Column("date_last_modified", sa.DateTime()))
    # Populate the date_last_modified column with the created date
    # or the lock_updated date if it exists.
    op.execute("UPDATE submission_metadata SET date_last_modified = created")
    op.execute(
        "UPDATE submission_metadata SET date_last_modified"
        + "= lock_updated WHERE lock_updated IS NOT NULL"
    )
    # Make the date_last_modified column non-nullable.
    op.alter_column("submission_metadata", "date_last_modified", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove column
    op.drop_column("submission_metadata", "date_last_modified")
    # ### end Alembic commands ###
