"""add part of and category to study class

Revision ID: 6fbdea177f37
Revises: d38130f3ca39
Create Date: 2023-12-21 14:54:03.767773

"""

from typing import Optional

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6fbdea177f37"
down_revision: Optional[str] = "d38130f3ca39"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "study",
        sa.Column(
            "children", postgresql.JSONB(astext_type=sa.Text()), nullable=True  # type: ignore
        ),
    )
    op.add_column(
        "study",
        sa.Column("part_of", postgresql.JSONB(astext_type=sa.Text()), nullable=True),  # type: ignore
    )
    op.add_column("study", sa.Column("study_category", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("study", "study_category")
    op.drop_column("study", "part_of")
    op.drop_column("study", "children")
    # ### end Alembic commands ###
