"""add part of and category to study class

Revision ID: 6fbdea177f37
Revises: d38130f3ca39
Create Date: 2023-12-21 14:54:03.767773

"""
from typing import Optional

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fbdea177f37'
down_revision: Optional[str] = 'd38130f3ca39'
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doi_info', 'doi_provider',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('study', sa.Column('part_of', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('study', sa.Column('study_category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'study_category')
    op.drop_column('study', 'part_of')
    op.alter_column('doi_info', 'doi_provider',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
