"""empty message

Revision ID: 7178fbceab2a
Revises: 28f470a18472
Create Date: 2021-08-26 13:28:42.974030

"""
from typing import Optional

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7178fbceab2a"
down_revision: Optional[str] = "28f470a18472"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_index",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("table", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("field", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_index")),
    )
    op.create_unique_constraint(op.f("uq_envo_ancestor_id"), "envo_ancestor", ["id", "ancestor_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_envo_ancestor_id"), "envo_ancestor", type_="unique")
    op.drop_table("search_index")
    # ### end Alembic commands ###
