"""empty message

Revision ID: 728268ae781c
Revises: 729a1c13fe30
Create Date: 2021-10-05 17:17:53.463142

"""
from typing import Optional

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "728268ae781c"
down_revision: Optional[str] = "729a1c13fe30"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("principal_investigator", sa.Column("orcid", sa.String(), nullable=True))
    op.add_column(
        "study",
        sa.Column("funding_sources", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "study",
        sa.Column("relevant_protocols", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "study",
        sa.Column(
            "has_credit_associations", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("principal_investigator", "orcid")
    op.drop_column("study", "has_credit_associations")
    op.drop_column("study", "funding_sources")
    op.drop_column("study", "relevant_protocols")
    # ### end Alembic commands ###
