"""Add submission status

Revision ID: 780ab86a4f27
Revises: 68c2c008f4cf
Create Date: 2022-04-14 17:19:51.309019

"""
from typing import Optional

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "780ab86a4f27"
down_revision: Optional[str] = "68c2c008f4cf"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("submission_metadata", sa.Column("status", sa.String(), nullable=True))
    op.execute("UPDATE submission_metadata SET status = 'in-progress';")
    op.alter_column("submission_metadata", "status", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("submission_metadata", "status")
    # ### end Alembic commands ###
