"""empty message

Revision ID: 7e990d499034
Revises: 97496561766f
Create Date: 2021-09-13 20:44:14.722662

"""
from typing import Optional

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e990d499034"
down_revision: Optional[str] = "97496561766f"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ko_term_to_pathway",
        sa.Column("term", sa.String(), nullable=False),
        sa.Column("pathway", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("term", "pathway", name=op.f("pk_ko_term_to_pathway")),
    )
    op.create_index(
        op.f("ix_ko_term_to_pathway_pathway"), "ko_term_to_pathway", ["pathway"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ko_term_to_pathway_pathway"), table_name="ko_term_to_pathway")
    op.drop_table("ko_term_to_pathway")
    # ### end Alembic commands ###
