"""Add nmdc_study_id to SubmissionMetadata

This field will store the NMDC study identifier for submissions.

Revision ID: 87821b18f9e3
Revises: 43ce041c88cb
Create Date: 2026-03-06 19:49:29.023313

"""
from typing import Optional

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87821b18f9e3'
down_revision: Optional[str] = '43ce041c88cb'
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_metadata', sa.Column('nmdc_study_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_metadata', 'nmdc_study_id')
    # ### end Alembic commands ###
