"""empty message

Revision ID: 97496561766f
Revises: 9a47f712c5fc
Create Date: 2021-09-13 16:53:46.404454

"""
from typing import Optional

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97496561766f"
down_revision: Optional[str] = "9a47f712c5fc"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_ko_term_to_module_module"), "ko_term_to_module", ["module"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ko_term_to_module_module"), table_name="ko_term_to_module")
    # ### end Alembic commands ###
