"""Update protocol_links column for study table

Revision ID: 997064dd504d
Revises: 3a68ea418acf
Create Date: 2025-05-20 19:55:48.595225

"""

from typing import Optional

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "997064dd504d"
down_revision: Optional[str] = "3a68ea418acf"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "study",
        sa.Column(
            "protocol_link",
            postgresql.JSONB(astext_type=sa.Text()),  # type:ignore
            nullable=True,
        ),
    )
    op.drop_column("study", "relevant_protocols")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "study",
        sa.Column(
            "relevant_protocols",
            postgresql.JSONB(astext_type=sa.Text()),  # type:ignore
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("study", "protocol_link")
    # ### end Alembic commands ###
