"""empty message

Revision ID: 9a47f712c5fc
Revises: 20e30659b752
Create Date: 2021-09-13 14:51:04.483806

"""
from typing import Optional

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a47f712c5fc"
down_revision: Optional[str] = "20e30659b752"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ko_term_to_module",
        sa.Column("term", sa.String(), nullable=False),
        sa.Column("module", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("term", "module", name=op.f("pk_ko_term_to_module")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ko_term_to_module")
    # ### end Alembic commands ###
