"""empty message

Revision ID: 9c4a29f70256
Revises: dddccd150962
Create Date: 2021-10-13 13:29:08.605594

"""
from typing import Optional

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c4a29f70256'
down_revision: Optional[str] = 'dddccd150962'
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mag', 'bin_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mag', 'bin_quality',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mag', 'completeness',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('mag', 'contamination',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('mag', 'gene_count',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('mag', 'num_16s',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('mag', 'num_23s',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('mag', 'num_5s',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('mag', 'num_tRNA',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('mag', 'number_of_contig',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mag', 'number_of_contig',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('mag', 'num_tRNA',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('mag', 'num_5s',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('mag', 'num_23s',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('mag', 'num_16s',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('mag', 'gene_count',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('mag', 'contamination',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('mag', 'completeness',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('mag', 'bin_quality',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mag', 'bin_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
