"""Make ended_at_time nullable

Revision ID: 9e6c9a57b893
Revises: 8993ccbbb9e4
Create Date: 2025-04-30 18:16:12.463808

"""

from typing import Optional

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9e6c9a57b893"
down_revision: Optional[str] = "8993ccbbb9e4"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "mags_analysis", "ended_at_time", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "metabolomics_analysis",
        "ended_at_time",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "metagenome_annotation",
        "ended_at_time",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "metagenome_assembly", "ended_at_time", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "metaproteomic_analysis",
        "ended_at_time",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "metatranscriptome", "ended_at_time", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "metatranscriptome_annotation",
        "ended_at_time",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "metatranscriptome_assembly",
        "ended_at_time",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "nom_analysis", "ended_at_time", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "read_based_analysis", "ended_at_time", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "reads_qc", "ended_at_time", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reads_qc", "ended_at_time", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "read_based_analysis", "ended_at_time", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "nom_analysis", "ended_at_time", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "metatranscriptome_assembly",
        "ended_at_time",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "metatranscriptome_annotation",
        "ended_at_time",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "metatranscriptome", "ended_at_time", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "metaproteomic_analysis",
        "ended_at_time",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "metagenome_assembly", "ended_at_time", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "metagenome_annotation",
        "ended_at_time",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "metabolomics_analysis",
        "ended_at_time",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "mags_analysis", "ended_at_time", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###
