"""empty message

Revision ID: a67ca461ab87
Revises: f7ab5b690b5e
Create Date: 2026-07-30 21:13:07.745388

"""

from typing import Optional

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a67ca461ab87"
down_revision: Optional[str] = "f7ab5b690b5e"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_biosample_env_broad_scale_id"), table_name="biosample")
    op.drop_index(op.f("idx_biosample_env_local_scale_id"), table_name="biosample")
    op.drop_index(op.f("idx_biosample_env_medium_id"), table_name="biosample")
    op.drop_index(
        op.f("ix_biosample_related_document_biosample_ids"),
        table_name="biosample_related_document",
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_biosample_related_document_document_type"), table_name="biosample_related_document"
    )
    op.drop_index(
        op.f("ix_biosample_related_document_downstream_neighbor_ids"),
        table_name="biosample_related_document",
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_biosample_related_document_high_level_type"),
        table_name="biosample_related_document",
    )
    op.drop_index(op.f("idx_envo_ancestor_ancestor_id"), table_name="envo_ancestor")
    op.add_column("mags_analysis", sa.Column("superseded_by", sa.String(), nullable=True))
    op.create_foreign_key(
        op.f("fk_mags_analysis_superseded_by_mags_analysis"),
        "mags_analysis",
        "mags_analysis",
        ["superseded_by"],
        ["id"],
    )
    op.add_column("metabolomics_analysis", sa.Column("superseded_by", sa.String(), nullable=True))
    op.create_foreign_key(
        op.f("fk_metabolomics_analysis_superseded_by_metabolomics_analysis"),
        "metabolomics_analysis",
        "metabolomics_analysis",
        ["superseded_by"],
        ["id"],
    )
    op.add_column("metagenome_annotation", sa.Column("superseded_by", sa.String(), nullable=True))
    op.create_foreign_key(
        op.f("fk_metagenome_annotation_superseded_by_metagenome_annotation"),
        "metagenome_annotation",
        "metagenome_annotation",
        ["superseded_by"],
        ["id"],
    )
    op.add_column("metagenome_assembly", sa.Column("superseded_by", sa.String(), nullable=True))
    op.create_foreign_key(
        op.f("fk_metagenome_assembly_superseded_by_metagenome_assembly"),
        "metagenome_assembly",
        "metagenome_assembly",
        ["superseded_by"],
        ["id"],
    )
    op.add_column("metaproteomic_analysis", sa.Column("superseded_by", sa.String(), nullable=True))
    op.create_foreign_key(
        op.f("fk_metaproteomic_analysis_superseded_by_metaproteomic_analysis"),
        "metaproteomic_analysis",
        "metaproteomic_analysis",
        ["superseded_by"],
        ["id"],
    )
    op.add_column("metatranscriptome", sa.Column("superseded_by", sa.String(), nullable=True))
    op.create_foreign_key(
        op.f("fk_metatranscriptome_superseded_by_metatranscriptome"),
        "metatranscriptome",
        "metatranscriptome",
        ["superseded_by"],
        ["id"],
    )
    op.add_column(
        "metatranscriptome_annotation", sa.Column("superseded_by", sa.String(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_metatranscriptome_annotation_superseded_by_metatranscriptome_annotation"),
        "metatranscriptome_annotation",
        "metatranscriptome_annotation",
        ["superseded_by"],
        ["id"],
    )
    op.add_column(
        "metatranscriptome_assembly", sa.Column("superseded_by", sa.String(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_metatranscriptome_assembly_superseded_by_metatranscriptome_assembly"),
        "metatranscriptome_assembly",
        "metatranscriptome_assembly",
        ["superseded_by"],
        ["id"],
    )
    op.add_column("nom_analysis", sa.Column("superseded_by", sa.String(), nullable=True))
    op.create_foreign_key(
        op.f("fk_nom_analysis_superseded_by_nom_analysis"),
        "nom_analysis",
        "nom_analysis",
        ["superseded_by"],
        ["id"],
    )
    op.add_column("read_based_analysis", sa.Column("superseded_by", sa.String(), nullable=True))
    op.create_foreign_key(
        op.f("fk_read_based_analysis_superseded_by_read_based_analysis"),
        "read_based_analysis",
        "read_based_analysis",
        ["superseded_by"],
        ["id"],
    )
    op.add_column("reads_qc", sa.Column("superseded_by", sa.String(), nullable=True))
    op.create_foreign_key(
        op.f("fk_reads_qc_superseded_by_reads_qc"),
        "reads_qc",
        "reads_qc",
        ["superseded_by"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_reads_qc_superseded_by_reads_qc"), "reads_qc", type_="foreignkey")
    op.drop_column("reads_qc", "superseded_by")
    op.drop_constraint(
        op.f("fk_read_based_analysis_superseded_by_read_based_analysis"),
        "read_based_analysis",
        type_="foreignkey",
    )
    op.drop_column("read_based_analysis", "superseded_by")
    op.drop_constraint(
        op.f("fk_nom_analysis_superseded_by_nom_analysis"), "nom_analysis", type_="foreignkey"
    )
    op.drop_column("nom_analysis", "superseded_by")
    op.drop_constraint(
        op.f("fk_metatranscriptome_assembly_superseded_by_metatranscriptome_assembly"),
        "metatranscriptome_assembly",
        type_="foreignkey",
    )
    op.drop_column("metatranscriptome_assembly", "superseded_by")
    op.drop_constraint(
        op.f("fk_metatranscriptome_annotation_superseded_by_metatranscriptome_annotation"),
        "metatranscriptome_annotation",
        type_="foreignkey",
    )
    op.drop_column("metatranscriptome_annotation", "superseded_by")
    op.drop_constraint(
        op.f("fk_metatranscriptome_superseded_by_metatranscriptome"),
        "metatranscriptome",
        type_="foreignkey",
    )
    op.drop_column("metatranscriptome", "superseded_by")
    op.drop_constraint(
        op.f("fk_metaproteomic_analysis_superseded_by_metaproteomic_analysis"),
        "metaproteomic_analysis",
        type_="foreignkey",
    )
    op.drop_column("metaproteomic_analysis", "superseded_by")
    op.drop_constraint(
        op.f("fk_metagenome_assembly_superseded_by_metagenome_assembly"),
        "metagenome_assembly",
        type_="foreignkey",
    )
    op.drop_column("metagenome_assembly", "superseded_by")
    op.drop_constraint(
        op.f("fk_metagenome_annotation_superseded_by_metagenome_annotation"),
        "metagenome_annotation",
        type_="foreignkey",
    )
    op.drop_column("metagenome_annotation", "superseded_by")
    op.drop_constraint(
        op.f("fk_metabolomics_analysis_superseded_by_metabolomics_analysis"),
        "metabolomics_analysis",
        type_="foreignkey",
    )
    op.drop_column("metabolomics_analysis", "superseded_by")
    op.drop_constraint(
        op.f("fk_mags_analysis_superseded_by_mags_analysis"), "mags_analysis", type_="foreignkey"
    )
    op.drop_column("mags_analysis", "superseded_by")
    op.create_index(
        op.f("idx_envo_ancestor_ancestor_id"), "envo_ancestor", ["ancestor_id"], unique=False
    )
    op.create_index(
        op.f("ix_biosample_related_document_high_level_type"),
        "biosample_related_document",
        ["high_level_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_biosample_related_document_downstream_neighbor_ids"),
        "biosample_related_document",
        ["downstream_neighbor_ids"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_biosample_related_document_document_type"),
        "biosample_related_document",
        [sa.literal_column("(document ->> 'type'::text)")],
        unique=False,
    )
    op.create_index(
        op.f("ix_biosample_related_document_biosample_ids"),
        "biosample_related_document",
        ["biosample_ids"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_biosample_env_medium_id"), "biosample", ["env_medium_id"], unique=False
    )
    op.create_index(
        op.f("idx_biosample_env_local_scale_id"), "biosample", ["env_local_scale_id"], unique=False
    )
    op.create_index(
        op.f("idx_biosample_env_broad_scale_id"), "biosample", ["env_broad_scale_id"], unique=False
    )
    # ### end Alembic commands ###
