"""empty message

Revision ID: ae7a3eba08c5
Revises: ffaec255fe68
Create Date: 2022-10-20 19:15:19.741270

"""
from typing import Optional

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7a3eba08c5'
down_revision: Optional[str] = 'ffaec255fe68'
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_envo_ancestor_id'), 'envo_ancestor', ['id', 'ancestor_id'])
    op.add_column('mag', sa.Column('num_trna', sa.BigInteger(), nullable=True))
    op.drop_column('mag', 'num_tRNA')
    op.add_column('mags_analysis', sa.Column('low_depth_contig_num', sa.BigInteger(), nullable=True))
    op.drop_column('mags_analysis', 'lowDepth_contig_num')
    op.add_column('metagenome_assembly', sa.Column('ctg_l50', sa.BigInteger(), nullable=True))
    op.add_column('metagenome_assembly', sa.Column('ctg_l90', sa.BigInteger(), nullable=True))
    op.add_column('metagenome_assembly', sa.Column('ctg_n50', sa.BigInteger(), nullable=True))
    op.add_column('metagenome_assembly', sa.Column('ctg_n90', sa.BigInteger(), nullable=True))
    op.add_column('metagenome_assembly', sa.Column('scaf_l50', sa.BigInteger(), nullable=True))
    op.add_column('metagenome_assembly', sa.Column('scaf_l90', sa.BigInteger(), nullable=True))
    op.add_column('metagenome_assembly', sa.Column('scaf_n50', sa.BigInteger(), nullable=True))
    op.add_column('metagenome_assembly', sa.Column('scaf_n90', sa.BigInteger(), nullable=True))
    op.add_column('metagenome_assembly', sa.Column('scaf_n_gt50k', sa.BigInteger(), nullable=True))
    op.add_column('metagenome_assembly', sa.Column('scaf_pct_gt50k', sa.BigInteger(), nullable=True))
    op.drop_column('metagenome_assembly', 'scaf_L90')
    op.drop_column('metagenome_assembly', 'scaf_pct_gt50K')
    op.drop_column('metagenome_assembly', 'scaf_N90')
    op.drop_column('metagenome_assembly', 'scaf_L50')
    op.drop_column('metagenome_assembly', 'ctg_L90')
    op.drop_column('metagenome_assembly', 'ctg_N90')
    op.drop_column('metagenome_assembly', 'ctg_L50')
    op.drop_column('metagenome_assembly', 'scaf_n_gt50K')
    op.drop_column('metagenome_assembly', 'scaf_N50')
    op.drop_column('metagenome_assembly', 'ctg_N50')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metagenome_assembly', sa.Column('ctg_N50', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('metagenome_assembly', sa.Column('scaf_N50', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('metagenome_assembly', sa.Column('scaf_n_gt50K', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('metagenome_assembly', sa.Column('ctg_L50', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('metagenome_assembly', sa.Column('ctg_N90', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('metagenome_assembly', sa.Column('ctg_L90', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('metagenome_assembly', sa.Column('scaf_L50', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('metagenome_assembly', sa.Column('scaf_N90', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('metagenome_assembly', sa.Column('scaf_pct_gt50K', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('metagenome_assembly', sa.Column('scaf_L90', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('metagenome_assembly', 'scaf_pct_gt50k')
    op.drop_column('metagenome_assembly', 'scaf_n_gt50k')
    op.drop_column('metagenome_assembly', 'scaf_n90')
    op.drop_column('metagenome_assembly', 'scaf_n50')
    op.drop_column('metagenome_assembly', 'scaf_l90')
    op.drop_column('metagenome_assembly', 'scaf_l50')
    op.drop_column('metagenome_assembly', 'ctg_n90')
    op.drop_column('metagenome_assembly', 'ctg_n50')
    op.drop_column('metagenome_assembly', 'ctg_l90')
    op.drop_column('metagenome_assembly', 'ctg_l50')
    op.add_column('mags_analysis', sa.Column('lowDepth_contig_num', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('mags_analysis', 'low_depth_contig_num')
    op.add_column('mag', sa.Column('num_tRNA', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('mag', 'num_trna')
    op.drop_constraint(op.f('uq_envo_ancestor_id'), 'envo_ancestor', type_='unique')
    # ### end Alembic commands ###
