"""add_email_to_users

Revision ID: b22c459110a0
Revises: 224db8f7e8df
Create Date: 2024-10-17 18:54:51.145636

"""

from typing import Optional

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b22c459110a0"
down_revision: Optional[str] = "224db8f7e8df"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_logins", sa.Column("email", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_logins", "email")
    # ### end Alembic commands ###
