"""consortia_add_homepage_website

Revision ID: b4b234bd55cf
Revises: 6fbdea177f37
Create Date: 2024-03-19 17:03:00.214065

"""

from typing import Optional

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b4b234bd55cf"
down_revision: Optional[str] = "6fbdea177f37"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "study",
        sa.Column(
            "homepage_website",
            postgresql.JSONB(astext_type=sa.Text()),  # type: ignore
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("study", "homepage_website")
    # ### end Alembic commands ###
