"""Use separate column for biosample EMSL IDs

Revision ID: b8f3bcb681a1
Revises: 0a3edcd64e1f
Create Date: 2023-04-04 20:30:37.491970

"""
from typing import Optional

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b8f3bcb681a1"
down_revision: Optional[str] = "0a3edcd64e1f"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "biosample",
        sa.Column(
            "emsl_biosample_identifiers",
            postgresql.JSONB(astext_type=sa.Text()),  # type:ignore
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("biosample", "emsl_biosample_identifiers")
    # ### end Alembic commands ###
