"""Auth token column

Revision ID: bbf330263df2
Revises: ae7a3eba08c5
Create Date: 2023-01-12 19:35:18.194042

"""
from typing import Optional

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbf330263df2'
down_revision: Optional[str] = 'ae7a3eba08c5'
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_logins', sa.Column('token', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_logins', 'token')
    # ### end Alembic commands ###
