"""Add table for metaT gene functions

Revision ID: c0b36f8dc4b8
Revises: d3d563e01a74
Create Date: 2024-07-25 14:24:16.657561

"""

from typing import Optional

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0b36f8dc4b8"
down_revision: Optional[str] = "d3d563e01a74"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metat_gene_function_aggregation",
        sa.Column("metatranscriptome_annotation_id", sa.String(), nullable=False),
        sa.Column("gene_function_id", sa.String(), nullable=False),
        sa.Column("count", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gene_function_id"],
            ["gene_function.id"],
            name=op.f("fk_metat_gene_function_aggregation_gene_function_id_gene_function"),
        ),
        sa.ForeignKeyConstraint(
            ["metatranscriptome_annotation_id"],
            ["metatranscriptome_annotation.id"],
            name=op.f(
                "fk_metat_gene_function_aggregation_metatranscriptome_annotation_id_metatranscriptome_annotation"  # noqa: E501
            ),
        ),
        sa.PrimaryKeyConstraint(
            "metatranscriptome_annotation_id",
            "gene_function_id",
            name=op.f("pk_metat_gene_function_aggregation"),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("metat_gene_function_aggregation")
    # ### end Alembic commands ###
