"""Add an index on `data_object_id` column of `file_download` table

Speed up computing download counts for data objecsts.

Revision ID: c27777e272d3
Revises: 6e6dec0daa7c
Create Date: 2025-02-28 20:38:34.018502

"""

from typing import Optional

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c27777e272d3"
down_revision: Optional[str] = "6e6dec0daa7c"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_file_download_data_object_id"), "file_download", ["data_object_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_download_data_object_id"), table_name="file_download")
    # ### end Alembic commands ###
