"""Create indexes on data_object_id columns in association tables

Revision ID: c4a3c1a90a62
Revises: da7be44d437c
Create Date: 2026-08-26 00:24:32.057431

"""

from typing import Optional

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4a3c1a90a62"
down_revision: Optional[str] = "da7be44d437c"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_mags_analysis_output_dobj_id",
        "mags_analysis_output_association",
        ["data_object_id"],
        unique=False,
    )
    op.create_index(
        "ix_metabolomics_analysis_output_dobj_id",
        "metabolomics_analysis_output_association",
        ["data_object_id"],
        unique=False,
    )
    op.create_index(
        "ix_metagenome_annotation_output_dobj_id",
        "metagenome_annotation_output_association",
        ["data_object_id"],
        unique=False,
    )
    op.create_index(
        "ix_metagenome_assembly_output_dobj_id",
        "metagenome_assembly_output_association",
        ["data_object_id"],
        unique=False,
    )
    op.create_index(
        "ix_metaproteomic_analysis_output_dobj_id",
        "metaproteomic_analysis_output_association",
        ["data_object_id"],
        unique=False,
    )
    op.create_index(
        "ix_metatranscriptome_annotation_output_dobj_id",
        "metatranscriptome_annotation_output_association",
        ["data_object_id"],
        unique=False,
    )
    op.create_index(
        "ix_metatranscriptome_assembly_output_dobj_id",
        "metatranscriptome_assembly_output_association",
        ["data_object_id"],
        unique=False,
    )
    op.create_index(
        "ix_metatranscriptome_output_dobj_id",
        "metatranscriptome_output_association",
        ["data_object_id"],
        unique=False,
    )
    op.create_index(
        "ix_nom_analysis_output_dobj_id",
        "nom_analysis_output_association",
        ["data_object_id"],
        unique=False,
    )
    op.create_index(
        "ix_omics_processing_output_dobj_id",
        "omics_processing_output_association",
        ["data_object_id"],
        unique=False,
    )
    op.create_index(
        "ix_read_based_analysis_output_dobj_id",
        "read_based_analysis_output_association",
        ["data_object_id"],
        unique=False,
    )
    op.create_index(
        "ix_reads_qc_output_dobj_id",
        "reads_qc_output_association",
        ["data_object_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reads_qc_output_dobj_id", table_name="reads_qc_output_association")
    op.drop_index(
        "ix_read_based_analysis_output_dobj_id", table_name="read_based_analysis_output_association"
    )
    op.drop_index(
        "ix_omics_processing_output_dobj_id", table_name="omics_processing_output_association"
    )
    op.drop_index("ix_nom_analysis_output_dobj_id", table_name="nom_analysis_output_association")
    op.drop_index(
        "ix_metatranscriptome_output_dobj_id", table_name="metatranscriptome_output_association"
    )
    op.drop_index(
        "ix_metatranscriptome_assembly_output_dobj_id",
        table_name="metatranscriptome_assembly_output_association",
    )
    op.drop_index(
        "ix_metatranscriptome_annotation_output_dobj_id",
        table_name="metatranscriptome_annotation_output_association",
    )
    op.drop_index(
        "ix_metaproteomic_analysis_output_dobj_id",
        table_name="metaproteomic_analysis_output_association",
    )
    op.drop_index(
        "ix_metagenome_assembly_output_dobj_id", table_name="metagenome_assembly_output_association"
    )
    op.drop_index(
        "ix_metagenome_annotation_output_dobj_id",
        table_name="metagenome_annotation_output_association",
    )
    op.drop_index(
        "ix_metabolomics_analysis_output_dobj_id",
        table_name="metabolomics_analysis_output_association",
    )
    op.drop_index("ix_mags_analysis_output_dobj_id", table_name="mags_analysis_output_association")
    # ### end Alembic commands ###
