"""update doi_info

Revision ID: d38130f3ca39
Revises: ded8702fcc7a
Create Date: 2023-12-05 21:50:30.315417

"""

from typing import Optional

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d38130f3ca39"
down_revision: Optional[str] = "ded8702fcc7a"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("doi_info", sa.Column("doi_provider", sa.String(), nullable=True))
    op.drop_column("study", "massive_study_identifiers")
    op.drop_column("study", "ess_dive_datasets")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "study",
        sa.Column(
            "ess_dive_datasets",
            postgresql.JSONB(astext_type=sa.Text()),  # type:ignore
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "study",
        sa.Column(
            "massive_study_identifiers",
            postgresql.JSONB(astext_type=sa.Text()),  # type:ignore
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("doi_info", "doi_provider")
    # ### end Alembic commands ###
