"""add bulk download rocrate cache column

Revision ID: da7be44d437c
Revises: 6a181e611245
Create Date: 2026-08-18 18:02:34.666770

"""
from typing import Optional

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da7be44d437c'
down_revision: Optional[str] = '6a181e611245'
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulk_download', sa.Column('rocrate_metadata_cache', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Temporary RO-Crate metadata cache populated when a bulk download is created and cleared after ZipStreamer retrieves it'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bulk_download', 'rocrate_metadata_cache')
    # ### end Alembic commands ###
