"""empty message

Revision ID: dc2a4cca7c66
Revises: 9a0ff33a4e6b
Create Date: 2025-09-11 21:38:15.666750

"""
from typing import Optional

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc2a4cca7c66'
down_revision: Optional[str] = '9a0ff33a4e6b'
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biosample', sa.Column('depth_min', sa.Float(), nullable=True))
    op.add_column('biosample', sa.Column('depth_max', sa.Float(), nullable=True))
    op.drop_column('biosample', 'depth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biosample', sa.Column('depth', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('biosample', 'depth_max')
    op.drop_column('biosample', 'depth_min')
    # ### end Alembic commands ###
