"""empty message

Revision ID: dddccd150962
Revises: cc01c50edacd
Create Date: 2021-10-08 18:38:45.027841

"""
from typing import Optional

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dddccd150962'
down_revision: Optional[str] = 'cc01c50edacd'
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_envo_ancestor_id'), 'envo_ancestor', ['id', 'ancestor_id'])
    op.add_column('study', sa.Column('ess_dive_datasets', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'ess_dive_datasets')
    op.drop_constraint(op.f('uq_envo_ancestor_id'), 'envo_ancestor', type_='unique')
    # ### end Alembic commands ###
