"""Create relation for submission roles

Revision ID: ded8702fcc7a
Revises: 0f87ba7add08
Create Date: 2024-01-10 22:34:09.294181

"""
from typing import Optional

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ded8702fcc7a"
down_revision: Optional[str] = "0f87ba7add08"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "submission_role",
        sa.Column("submission_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_orcid", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "editor",
                "owner",
                "viewer",
                "metadata_contributor",
                "reviewer",
                name="submissioneditorrole",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submission_metadata.id"],
            name=op.f("fk_submission_role_submission_id_submission_metadata"),
        ),
        sa.PrimaryKeyConstraint("submission_id", "user_orcid", name=op.f("pk_submission_role")),
        sa.UniqueConstraint(
            "submission_id", "user_orcid", name=op.f("uq_submission_role_submission_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("submission_role")
    # ### end Alembic commands ###
