"""Remove FK relationship from workflow classes to omics processing.

Revision ID: ffa58e5f59fe
Revises: 3b2b6e524b47
Create Date: 2025-07-18 17:32:20.220631

"""

from typing import Optional

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffa58e5f59fe"
down_revision: Optional[str] = "3b2b6e524b47"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_mags_analysis_omics_processing_id_omics_processing", "mags_analysis", type_="foreignkey"
    )
    op.drop_column("mags_analysis", "omics_processing_id")
    op.drop_constraint(
        "fk_metabolomics_analysis_omics_processing_id_omics_processing",
        "metabolomics_analysis",
        type_="foreignkey",
    )
    op.drop_column("metabolomics_analysis", "omics_processing_id")
    op.drop_constraint(
        "fk_metagenome_annotation_omics_processing_id_omics_processing",
        "metagenome_annotation",
        type_="foreignkey",
    )
    op.drop_column("metagenome_annotation", "omics_processing_id")
    op.drop_constraint(
        "fk_metagenome_assembly_omics_processing_id_omics_processing",
        "metagenome_assembly",
        type_="foreignkey",
    )
    op.drop_column("metagenome_assembly", "omics_processing_id")
    op.drop_constraint(
        "fk_metaproteomic_analysis_omics_processing_id_omics_processing",
        "metaproteomic_analysis",
        type_="foreignkey",
    )
    op.drop_column("metaproteomic_analysis", "omics_processing_id")
    op.drop_constraint(
        "fk_metatranscriptome_omics_processing_id_omics_processing",
        "metatranscriptome",
        type_="foreignkey",
    )
    op.drop_column("metatranscriptome", "omics_processing_id")
    op.drop_constraint(
        "fk_metatranscriptome_annotation_omics_processing_id_omi_bc1a",
        "metatranscriptome_annotation",
        type_="foreignkey",
    )
    op.drop_column("metatranscriptome_annotation", "omics_processing_id")
    op.drop_constraint(
        "fk_metatranscriptome_assembly_omics_processing_id_omics_d648",
        "metatranscriptome_assembly",
        type_="foreignkey",
    )
    op.drop_column("metatranscriptome_assembly", "omics_processing_id")
    op.drop_constraint(
        "fk_nom_analysis_omics_processing_id_omics_processing", "nom_analysis", type_="foreignkey"
    )
    op.drop_column("nom_analysis", "omics_processing_id")
    op.drop_constraint(
        "fk_read_based_analysis_omics_processing_id_omics_processing",
        "read_based_analysis",
        type_="foreignkey",
    )
    op.drop_column("read_based_analysis", "omics_processing_id")
    op.drop_constraint(
        "fk_reads_qc_omics_processing_id_omics_processing", "reads_qc", type_="foreignkey"
    )
    op.drop_column("reads_qc", "omics_processing_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reads_qc",
        sa.Column("omics_processing_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_reads_qc_omics_processing_id_omics_processing",
        "reads_qc",
        "omics_processing",
        ["omics_processing_id"],
        ["id"],
    )
    op.add_column(
        "read_based_analysis",
        sa.Column("omics_processing_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_read_based_analysis_omics_processing_id_omics_processing",
        "read_based_analysis",
        "omics_processing",
        ["omics_processing_id"],
        ["id"],
    )
    op.add_column(
        "nom_analysis",
        sa.Column("omics_processing_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_nom_analysis_omics_processing_id_omics_processing",
        "nom_analysis",
        "omics_processing",
        ["omics_processing_id"],
        ["id"],
    )
    op.add_column(
        "metatranscriptome_assembly",
        sa.Column("omics_processing_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_metatranscriptome_assembly_omics_processing_id_omics_d648",
        "metatranscriptome_assembly",
        "omics_processing",
        ["omics_processing_id"],
        ["id"],
    )
    op.add_column(
        "metatranscriptome_annotation",
        sa.Column("omics_processing_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_metatranscriptome_annotation_omics_processing_id_omi_bc1a",
        "metatranscriptome_annotation",
        "omics_processing",
        ["omics_processing_id"],
        ["id"],
    )
    op.add_column(
        "metatranscriptome",
        sa.Column("omics_processing_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_metatranscriptome_omics_processing_id_omics_processing",
        "metatranscriptome",
        "omics_processing",
        ["omics_processing_id"],
        ["id"],
    )
    op.add_column(
        "metaproteomic_analysis",
        sa.Column("omics_processing_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_metaproteomic_analysis_omics_processing_id_omics_processing",
        "metaproteomic_analysis",
        "omics_processing",
        ["omics_processing_id"],
        ["id"],
    )
    op.add_column(
        "metagenome_assembly",
        sa.Column("omics_processing_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_metagenome_assembly_omics_processing_id_omics_processing",
        "metagenome_assembly",
        "omics_processing",
        ["omics_processing_id"],
        ["id"],
    )
    op.add_column(
        "metagenome_annotation",
        sa.Column("omics_processing_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_metagenome_annotation_omics_processing_id_omics_processing",
        "metagenome_annotation",
        "omics_processing",
        ["omics_processing_id"],
        ["id"],
    )
    op.add_column(
        "metabolomics_analysis",
        sa.Column("omics_processing_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_metabolomics_analysis_omics_processing_id_omics_processing",
        "metabolomics_analysis",
        "omics_processing",
        ["omics_processing_id"],
        ["id"],
    )
    op.add_column(
        "mags_analysis",
        sa.Column("omics_processing_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_mags_analysis_omics_processing_id_omics_processing",
        "mags_analysis",
        "omics_processing",
        ["omics_processing_id"],
        ["id"],
    )
    # ### end Alembic commands ###
