<script lang="ts">
import { defineComponent } from '@vue/composition-api';
import {
  multiOmicsForm, templateChoiceDisabled, contextForm,
} from '../store';

export default defineComponent({
  props: {
    legend: {
      type: String,
      default: 'Data Types',
    },
  },
  setup() {
    return {
      multiOmicsForm,
      contextForm,
      templateChoiceDisabled,
    };
  },

});

</script>

<template>
  <div

    class="text-h6 mt-4"
  >
    <legend
      class="v-label theme--light mb-2"
      style="font-size: 14px;"
    >
      {{ legend }}
    </legend>
    <v-checkbox
      v-model="multiOmicsForm.omicsProcessingTypes"
      label="Metagenome"
      value="mg"
      :disabled="templateChoiceDisabled"
      hide-details
    />
    <div
      v-if="multiOmicsForm.omicsProcessingTypes.includes('mg')"
      class="v-label theme--light my-2 mx-8"
      style="font-size: 14px;"
    >
      NMDC currently supports external sequencing data that is comparable to data generated by the Joint Genome Institute (JGI):
      <ul
        class="my-2"
      >
        <li
          class="my-2"
        >
          Kapa Biosystems HyperPrep library preparation kit (Roche)
        </li>
        <li
          class="my-2"
        >
          Illumina NovaSeq X with a 2x150 run mode
        </li>
      </ul>
      Additional details about <a href="https://doi.org/10.1128/msystems.00804-20">metagenome processing</a> are available.
      If you have questions please contact <a href="mailto:support@microbiomedata.org">support@microbiomedata.org</a>
      <v-radio-group
        v-model="multiOmicsForm.mgCompatible"
        label="Is the generated data compatible? *"
      >
        <v-radio
          label="No"
          :value="false"
        />
        <v-radio
          label="Yes"
          :value="true"
        />
      </v-radio-group>
      <v-radio-group
        v-if="multiOmicsForm.mgCompatible"
        v-model="multiOmicsForm.mgInterleaved"
        label="Is the data in interleaved format? *"
      >
        <v-radio
          label="No"
          :value="false"
        />
        <v-radio
          label="Yes"
          :value="true"
        />
      </v-radio-group>
    </div>
    <v-checkbox
      v-model="multiOmicsForm.omicsProcessingTypes"
      label="Metatranscriptome"
      value="mt"
      :disabled="templateChoiceDisabled"
      hide-details
    />
    <div
      v-if="multiOmicsForm.omicsProcessingTypes.includes('mt')"
      class="v-label theme--light my-2 mx-8"
      style="font-size: 14px;"
    >
      NMDC currently supports external sequencing data that is comparable to data generated by the Joint Genome Institute (JGI):
      <ul
        class="my-2"
      >
        <li
          class="my-2"
        >
          Qiagen FastSelect 5S/16S/23s for bacterial rRNA depletion kit
        </li>
        <li
          class="my-2"
        >
          Illumina TruSeq Stranded Total RNA HT sample prep kit
        </li>
        <li
          class="my-2"
        >
          Illumina NovaSeq X with a 2x150 run mode
        </li>
      </ul>
      Additional details about <a href="https://jgi.doe.gov/wp-content/uploads/2022/03/20220125_metatranscriptome_planning_overview-FINAL.pdf">metatranscriptomes processing</a> are available.
      If you have questions please contact <a href="mailto:support@microbiomedata.org">support@microbiomedata.org</a>
      <v-radio-group
        v-model="multiOmicsForm.mtCompatible"
        label="Is the generated data compatible? *"
      >
        <v-radio
          label="No"
          :value="false"
        />
        <v-radio
          label="Yes"
          :value="true"
        />
      </v-radio-group>
      <v-radio-group
        v-if="multiOmicsForm.mtCompatible"
        v-model="multiOmicsForm.mtInterleaved"
        label="Is the dasta in interleaved format? *"
      >
        <v-radio
          label="No"
          :value="false"
        />
        <v-radio
          label="Yes"
          :value="true"
        />
      </v-radio-group>
    </div>

    <v-checkbox
      v-model="multiOmicsForm.omicsProcessingTypes"
      label="Metaproteome"
      value="mp"
      :disabled="templateChoiceDisabled"
      hide-details
    />
    <v-checkbox
      v-model="multiOmicsForm.omicsProcessingTypes"
      label="Metabolome"
      value="mb"
      :disabled="templateChoiceDisabled"
      hide-details
    />
    <v-checkbox
      v-model="multiOmicsForm.omicsProcessingTypes"
      label="Natural Organic Matter (FT-ICR MS)"
      value="nom"
      :disabled="templateChoiceDisabled"
      hide-details
    />
  </div>
</template>
