<script lang="ts">
import { defineComponent } from 'vue';
import { HARMONIZER_TEMPLATES } from '@/views/SubmissionPortal/types';
import {
  multiOmicsForm, templateHasData,
} from '../store';
import ExternalProtocolForm from './ExternalProtocolForm.vue';

export default defineComponent({
  components: {
    ExternalProtocolForm,
  },
  props: {
    legend: {
      type: String,
      default: 'Data Types',
    },
    showDataCompatibilityQuestions: {
      type: Boolean,
      default: true,
    },
  },
emits: ['revalidate'],
  setup() {
    const dataCaveat = 'You may proceed with your submission for sample metadata capture. However, there will not be place to provide information about your existing sequencing data as the methods are not supported by NMDC Workflows';

    return {
      dataCaveat,
      multiOmicsForm,
      HARMONIZER_TEMPLATES,
      templateHasData,
    };
  },

});

</script>

<template>
  <div class="my-4">
    <v-label class="ml-4">
      {{ legend }}
    </v-label>
    <div class="ml-2">
      <v-checkbox
        v-model="multiOmicsForm.omicsProcessingTypes"
        label="Metagenome"
        value="mg"
        :disabled="templateHasData(HARMONIZER_TEMPLATES.data_mg?.sampleDataSlot) || templateHasData(HARMONIZER_TEMPLATES.data_mg_interleaved?.sampleDataSlot) || undefined"
        hide-details
        @change="$emit('revalidate')"
      />
      <div
        v-if="showDataCompatibilityQuestions && multiOmicsForm.omicsProcessingTypes.includes('mg')"
        class="mx-8"
      >
        <div class="text-body-2 mb-4 pl-4">
          NMDC currently supports external sequencing data that is comparable to data generated by the Joint Genome Institute (JGI):
          <ul class="pl-8">
            <li>
              Kapa Biosystems HyperPrep library preparation kit (Roche)
            </li>
            <li>
              Illumina NovaSeq X with a 2x150 run mode
            </li>
          </ul>
          Additional details about <a href="https://doi.org/10.1128/msystems.00804-20">metagenome processing</a> are available.
          If you have questions please contact <a href="mailto:support@microbiomedata.org">support@microbiomedata.org</a>
        </div>
        <v-radio-group
          v-model="multiOmicsForm.mgCompatible"
          label="Is the generated data compatible? *"
          :rules="[v => (v === true || v === false) || 'This field is required']"
          :disabled="templateHasData(HARMONIZER_TEMPLATES.data_mg?.sampleDataSlot) || templateHasData(HARMONIZER_TEMPLATES.data_mg_interleaved?.sampleDataSlot) || undefined"
          @change="$emit('revalidate')"
        >
          <v-radio
            :value="false"
          >
            <template #label>
              <span>
                No
              </span>
              <v-tooltip
                right
                class="x-2"
                max-width="500"
              >
                <template #activator="{ props }">
                  <v-icon
                    class="ml-2"
                    color="grey"
                    size="small"
                    v-bind="props"
                  >
                    mdi-help-circle
                  </v-icon>
                </template>
                <span>
                  {{ dataCaveat }}
                </span>
              </v-tooltip>
            </template>
          </v-radio>
          <v-radio
            label="Yes"
            :value="true"
          />
        </v-radio-group>
        <v-radio-group
          v-if="multiOmicsForm.mgCompatible"
          v-model="multiOmicsForm.mgInterleaved"
          label="Is the data in interleaved format? *"
          :disabled="templateHasData(HARMONIZER_TEMPLATES.data_mg?.sampleDataSlot) || templateHasData(HARMONIZER_TEMPLATES.data_mg_interleaved?.sampleDataSlot) || undefined"
          :rules="[v => (v === true || v === false) || 'This field is required']"
        >
          <v-radio
            label="No"
            :value="false"
          />
          <v-radio
            label="Yes"
            :value="true"
          />
        </v-radio-group>
      </div>
      <v-checkbox
        v-model="multiOmicsForm.omicsProcessingTypes"
        label="Metatranscriptome"
        value="mt"
        :disabled="templateHasData(HARMONIZER_TEMPLATES.data_mt?.sampleDataSlot) || templateHasData(HARMONIZER_TEMPLATES.data_mt_interleaved?.sampleDataSlot) || undefined"
        hide-details
        @change="$emit('revalidate')"
      />
      <div
        v-if="showDataCompatibilityQuestions && multiOmicsForm.omicsProcessingTypes.includes('mt')"
        class="mx-8"
      >
        <div class="text-body-2 mb-4 pl-4">
          NMDC currently supports external sequencing data that is comparable to data generated by the Joint Genome Institute (JGI):
          <ul class="pl-8">
            <li>
              Qiagen FastSelect 5S/16S/23s for bacterial rRNA depletion kit
            </li>
            <li>
              Illumina TruSeq Stranded Total RNA HT sample prep kit
            </li>
            <li>
              Illumina NovaSeq X with a 2x150 run mode
            </li>
          </ul>
          Additional details about <a href="https://jgi.doe.gov/wp-content/uploads/2022/03/20220125_metatranscriptome_planning_overview-FINAL.pdf">metatranscriptomes processing</a> are available.
          If you have questions please contact <a href="mailto:support@microbiomedata.org">support@microbiomedata.org</a>
        </div>
        <v-radio-group
          v-model="multiOmicsForm.mtCompatible"
          label="Is the generated data compatible? *"
          :rules="[v => (v === true || v === false) || 'This field is required']"
          :disabled="templateHasData(HARMONIZER_TEMPLATES.data_mt?.sampleDataSlot) || templateHasData(HARMONIZER_TEMPLATES.data_mt_interleaved?.sampleDataSlot) || undefined"
          @change="$emit('revalidate')"
        >
          <v-radio
            :value="false"
          >
            <template #label>
              <span>
                No
              </span>
              <v-tooltip
                right
                class="x-2"
                max-width="500"
              >
                <template #activator="{ props }">
                  <v-icon
                    class="ml-2"
                    color="grey"
                    size="small"
                    v-bind="props"
                  >
                    mdi-help-circle
                  </v-icon>
                </template>
                <span>
                  {{ dataCaveat }}
                </span>
              </v-tooltip>
            </template>
          </v-radio>
          <v-radio
            label="Yes"
            :value="true"
          />
        </v-radio-group>
        <v-radio-group
          v-if="multiOmicsForm.mtCompatible"
          v-model="multiOmicsForm.mtInterleaved"
          label="Is the data in interleaved format? *"
          :disabled="templateHasData(HARMONIZER_TEMPLATES.data_mt?.sampleDataSlot) || templateHasData(HARMONIZER_TEMPLATES.data_mt_interleaved?.sampleDataSlot) || undefined"
          :rules="[v => (v === true || v === false) || 'This field is required']"
        >
          <v-radio
            label="No"
            :value="false"
          />
          <v-radio
            label="Yes"
            :value="true"
          />
        </v-radio-group>
      </div>

      <v-checkbox
        v-model="multiOmicsForm.omicsProcessingTypes"
        label="Metaproteome"
        value="mp"
        hide-details
      />
      <ExternalProtocolForm
        v-if="multiOmicsForm.omicsProcessingTypes.includes('mp')"
        data-type="mpProtocols"
      />
      <v-checkbox
        v-model="multiOmicsForm.omicsProcessingTypes"
        label="Metabolome"
        value="mb"
        hide-details
      />
      <ExternalProtocolForm
        v-if="multiOmicsForm.omicsProcessingTypes.includes('mb')"
        data-type="mbProtocols"
      />
      <v-checkbox
        v-model="multiOmicsForm.omicsProcessingTypes"
        label="Natural Organic Matter (FT-ICR MS)"
        value="nom"
        hide-details
      />
      <ExternalProtocolForm
        v-if="multiOmicsForm.omicsProcessingTypes.includes('nom')"
        data-type="nomProtocols"
      />
      <v-checkbox
        v-model="multiOmicsForm.omicsProcessingTypes"
        label="Lipidome"
        value="lipidome-emsl"
        hide-details
      />
      <ExternalProtocolForm
        v-if="multiOmicsForm.omicsProcessingTypes.includes('lipidome-emsl')"
        data-type="lipProtocols"
      />
    </div>
  </div>
</template>
