<script lang="ts">
import { defineComponent, ref, nextTick } from '@vue/composition-api';
import {
  multiOmicsForm, templateChoiceDisabled, contextForm,
} from '../store';
import Definitions from '@/definitions';
import SubmissionContextShippingForm from './SubmissionContextShippingForm.vue';

export default defineComponent({
  components: {
    SubmissionContextShippingForm,

  },
  props: {
    label: {
      type: String,
      default: 'Data generated ',
    },
  },

  setup() {
    const doiRequiredRules = () => [(v: string) => {
      const valid = !!v || (!contextForm.facilityGenerated && contextForm.dataGenerated) || (contextForm.unknownDoi && !contextForm.dataGenerated);
      return valid || 'An award DOI is required if data was or is going to be generated by a DOE facility.';
    }];

    function addAwardDoi() {
      if (contextForm.awardDois === null || contextForm.awardDois.length === 0) {
        contextForm.awardDois = [''];
      } else {
        contextForm.awardDois.push('');
      }
    }

    function removeAwardDoi(i: number) {
      if (contextForm.awardDois === null) {
        contextForm.awardDois = [''];
      }
      if ((contextForm.facilities.length < contextForm.awardDois.length && !contextForm.dataGenerated) || (contextForm.facilityGenerated && contextForm.dataGenerated && contextForm.awardDois.length > 1) || (!contextForm.facilityGenerated && contextForm.dataGenerated)) {
        contextForm.awardDois.splice(i, 1);
      }
    }

    const formRef = ref();

    const revalidate = () => {
      nextTick(() => formRef.value.validate());
    };

    return {
      addAwardDoi,
      Definitions,
      doiRequiredRules,
      multiOmicsForm,
      contextForm,
      removeAwardDoi,
      revalidate,
      templateChoiceDisabled,
    };
  },

});
</script>

<template>
  <div>
    <legend
      class="v-label theme--light mb-2"
      style="font-size: 14px;"
    >
      Which facility?
    </legend>
    <v-checkbox
      v-model="contextForm.facilities"
      label="EMSL"
      value="EMSL"
      hide-details
      class="mb-2 mt-0"
    />
    <div
      v-if="contextForm.facilities.includes('EMSL')"
      class="mb-4 ml-4"
    >
      <div
        :key="`awardDoi${i}`"
        class="d-flex"
      >
        <v-card
          class="d-flex flex-column grow px-4 mb-4"
          flat
        >
          <v-text-field
            v-if="contextForm.facilities.includes('EMSL')"
            v-model="multiOmicsForm.studyNumber"
            :rules="[
              v => !!v || 'EMSL Proposal Number is required when processing was done at EMSL',
              v => /^\d{5}$/.test(v) || 'EMSL Proposal Number must be a 5 digit numerical value'
            ]"
            hint="EMSL Proposal Number is required when processing was done at EMSL"
            persistent-hint
            label="EMSL Proposal Number *"
            class="mt-4"
            outlined
            validate-on-blur
            dense
          />
          <div class="d-flex">
            <v-text-field
              v-if="contextForm.facilities.includes('EMSL')"
              v-model="contextForm.awardDois"
              label="EMSL Award DOI *"
              :hint="Definitions.doi"
              :rules="doiRequiredRules()"
              persistent-hint
              validate-on-blur
              outlined
              dense
              @change="revalidate"
            >
              <template #message="{ message }">
                <span v-html="message" />
              </template>
            </v-text-field>
          </div>
          <v-checkbox
            v-if="!contextForm.dataGenerated && contextForm.facilities.includes('EMSL')"
            v-model="contextForm.unknownDoi"
            :label="`I don't know my award DOI`"
            :hint="Definitions.unknownDoi"
            persistent-hint
            @change="revalidate"
          />
        </v-card>
      </div>
      <v-radio-group
        v-if="contextForm.dataGenerated === false && contextForm.facilities.includes('EMSL')"
        v-model="contextForm.ship"
        label="Will samples be shipped? *"
        :rules="[v => (v === true || v === false) || 'This field is required']"
        @change="revalidate"
      >
        <v-radio
          label="No"
          :value="false"
        />
        <v-radio
          label="Yes"
          :value="true"
        />
      </v-radio-group>
      <submission-context-shipping-form
        v-if="contextForm.dataGenerated === false && contextForm.ship && contextForm.facilities.includes('EMSL')"
      />
      <div
        class="v-label theme--light mt-6"
        style="font-size: 14px;"
      >
        Data types?
      </div>

      <v-checkbox
        v-model="multiOmicsForm.omicsProcessingTypes"
        label="Metaproteome"
        value="mp-emsl"
        :disabled="templateChoiceDisabled"
        hide-details
      />
      <v-checkbox
        v-model="multiOmicsForm.omicsProcessingTypes"
        label="Metabolome"
        value="mb-emsl"
        :disabled="templateChoiceDisabled"
        hide-details
      />
      <v-checkbox
        v-model="multiOmicsForm.omicsProcessingTypes"
        label="Natural Organic Matter (FT-ICR MS)"
        value="nom-emsl"
        :disabled="templateChoiceDisabled"
        hide-details
      />
    </div>
    <v-checkbox
      v-model="contextForm.facilities"
      label="JGI"
      value="JGI"
      hide-details
      class="mb-2 mt-0"
    />
    <div
      v-if="contextForm.facilities.includes('JGI')"
      class="my-4 ml-4"
    >
      <div
        :key="`awardDoi${i}`"
        class="d-flex"
      >
        <v-card
          class="d-flex flex-column grow pa-4 mb-4"
          flat
        >
          <v-text-field
            v-if="contextForm.facilities.includes('JGI')"
            v-model="multiOmicsForm.studyNumber"
            :rules="[ v => !!v || 'JGI Proposal Number is required when processing was done at JGI' ]"
            hint="JGI Proposal Number is required when processing was done at JGI"
            persistent-hint
            label="JGI Proposal Number *"
            class="mt-4"
            outlined
            validate-on-blur
            dense
          />
          <div class="d-flex">
            <v-text-field
              v-if="contextForm.facilities.includes('JGI')"
              v-model="contextForm.awardDois"
              label="JGI Award DOI *"
              :hint="Definitions.doi"
              :rules="doiRequiredRules()"
              persistent-hint
              validate-on-blur
              outlined
              dense
              @change="revalidate"
            >
              <template #message="{ message }">
                <span v-html="message" />
              </template>
            </v-text-field>
          </div>
          <v-checkbox
            v-if="!contextForm.dataGenerated && contextForm.facilities.includes('JGI')"
            v-model="contextForm.unknownDoi"
            class="pa-0 mt-4"
            :label="`I don't know my award DOI`"
            :hint="Definitions.unknownDoi"
            persistent-hint
            @change="revalidate"
          />
        </v-card>
      </div>
      <div
        class="v-label theme--light mb-2"
        style="font-size: 14px;"
      >
        Data types?
      </div>
      <v-checkbox
        v-model="multiOmicsForm.omicsProcessingTypes"
        label="Metagenome"
        value="mg-jgi"
        :disabled="templateChoiceDisabled"
        hide-details
      />
      <v-checkbox
        v-model="multiOmicsForm.omicsProcessingTypes"
        label="Metagenome (Long Read)"
        value="mg-lr-jgi"
        :disabled="templateChoiceDisabled"
        hide-details
      />
      <v-checkbox
        v-model="multiOmicsForm.omicsProcessingTypes"
        label="Metatranscriptome"
        value="mt-jgi"
        :disabled="templateChoiceDisabled"
        hide-details
      />
      <v-checkbox
        v-model="multiOmicsForm.omicsProcessingTypes"
        label="Metabolome"
        value="mb-jgi"
        disabled
        hide-details
      />
      <v-text-field
        v-if="multiOmicsForm.omicsProcessingTypes.some((v) => v.endsWith('jgi'))"
        v-model="multiOmicsForm.JGIStudyId"
        :rules="[
          v => !!v || 'JGI Proposal ID/Study ID is required when processing was done at JGI',
          v => /^\d{6}$/.test(v) || 'JGI Proposal ID/Study ID must be a 6 digit numerical value'
        ]"
        label="JGI Proposal ID/Study ID *"
        hint="This is the 6 digit ID assigned to your JGI Proposal and is required when completing metadata for samples to be sent to JGI for sequencing."
        persistent-hint
        class="mt-4"
        outlined
        validate-on-blur
        dense
      />
    </div>
  </div>
</template>
