<script lang="ts">
import {
  defineComponent,
  ref,
  onMounted,
  watch,
  nextTick,
} from '@vue/composition-api';

import Definitions from '@/definitions';
import {
  multiOmicsForm, multiOmicsFormValid, multiOmicsAssociations, templateChoiceDisabled, canEditSubmissionMetadata, addAwardDoi, removeAwardDoi,
} from '../store';
import { AwardTypes } from '@/views/SubmissionPortal/types';

import SubmissionDocsLink from './SubmissionDocsLink.vue';
import SubmissionPermissionBanner from './SubmissionPermissionBanner.vue';
import DataTypes from './DataTypes.vue';
import DoeFacility from './DoeFacility.vue';

const OTHER = 'OTHER';

export default defineComponent({
  components: {
    DataTypes,
    DoeFacility,
    SubmissionDocsLink,
    SubmissionPermissionBanner,
  },
  setup() {
    const formRef = ref();

    function reValidate() {
      formRef.value.validate();
    }

    const projectAwardValidationRules = () => [(v: string | undefined) => {
      const facilityChosen = multiOmicsForm.facilities.length > 0;
      if (!facilityChosen) {
        return true;
      }
      const awardChosen = v !== undefined;
      if (!awardChosen) {
        return 'If submitting to a use facility, this field is required.';
      }
      return true;
    }];
    const otherAwardValidationRules = () => [(v: string | undefined) => {
      const facilityChosen = multiOmicsForm.facilities.length > 0;
      const awardChosen = multiOmicsForm.award !== undefined;
      if (!facilityChosen && !awardChosen) {
        return true;
      }
      if (!awardChosen || multiOmicsForm.award !== OTHER) {
        return true;
      }
      const inputEmpty = v === undefined || v.trim().length === 0;
      if (inputEmpty) {
        return 'Please enter the kind of project award.';
      }
      return true;
    }];
    const doiRequiredRules = () => [(v: string) => {
      const valid = !!v || (!multiOmicsForm.facilityGenerated && multiOmicsForm.dataGenerated) || (multiOmicsForm.unknownDoi && !multiOmicsForm.dataGenerated);
      return valid || 'An award DOI is required if data was or is going to be generated by a DOE facility.';
    }];
    const revalidate = () => {
      nextTick(() => formRef.value.validate());
    };

    function resetFields(field: string) {
      if (field === 'dataGenerated') {
        multiOmicsForm.facilityGenerated = undefined;
        multiOmicsForm.doe = undefined;
      }
      multiOmicsForm.award = undefined;
      multiOmicsForm.otherAward = undefined;
      multiOmicsForm.mgCompatible = undefined;
      multiOmicsForm.mgInterleaved = undefined;
      multiOmicsForm.omicsProcessingTypes = [];
      multiOmicsForm.mtCompatible = undefined;
      multiOmicsForm.mtInterleaved = undefined;
      multiOmicsForm.facilities = [];
      revalidate();
    }

    watch(
      () => multiOmicsForm.award,
      (award) => {
        const awardTypes = Object.values(AwardTypes) as string[];
        if (award && awardTypes.includes(award)) {
          multiOmicsForm.otherAward = '';
        }
        revalidate();
      },
    );

    onMounted(() => {
      formRef.value.validate();
    });

    return {
      OTHER,
      addAwardDoi,
      removeAwardDoi,
      projectAwardValidationRules,
      otherAwardValidationRules,
      doiRequiredRules,
      revalidate,
      resetFields,
      formRef,
      multiOmicsForm,
      multiOmicsAssociations,
      multiOmicsFormValid,
      Definitions,
      templateChoiceDisabled,
      /* functions */
      reValidate,
      canEditSubmissionMetadata,
    };
  },
});
</script>

<template>
  <div>
    <div class="text-h2">
      Multi-omics Data
      <submission-docs-link anchor="multi-omics-data" />
    </div>
    <div class="text-h5">
      Information about the type of samples being submitted.
    </div>
    <submission-permission-banner
      v-if="!canEditSubmissionMetadata()"
    />
    <v-form
      ref="formRef"
      v-model="multiOmicsFormValid"
      class="my-6 mb-10"
      style="max-width: 1000px;"
      :disabled="!canEditSubmissionMetadata()"
    >
      <v-radio-group
        v-model="multiOmicsForm.dataGenerated"
        label="Have data already been generated for your study? *"
        :rules="[v => (v === true || v === false) || 'This field is required']"
        @change="resetFields('dataGenerated')"
      >
        <v-radio
          label="No"
          :value="false"
        />
        <v-radio
          label="Yes"
          :value="true"
        />
      </v-radio-group>
      <v-radio-group
        v-if="multiOmicsForm.dataGenerated"
        v-model="multiOmicsForm.facilityGenerated"
        label="Was data generated at a DOE user facility (JGI, EMSL)? *"
        :rules="[v => (v === true || v === false) || 'This field is required']"
        @change="resetFields('facilityGenerated')"
      >
        <v-radio
          label="No"
          :value="false"
          hide-details
          class="mb-2 mt-0"
        />
        <v-radio
          label="Yes"
          :value="true"
          hide-details
          class="mb-2 mt-0"
        />
      </v-radio-group>
      <div
        v-if="multiOmicsForm.dataGenerated === true && multiOmicsForm.facilityGenerated"
      >
        <DoeFacility />
      </div>
      <v-radio-group
        v-if="multiOmicsForm.dataGenerated === false"
        v-model="multiOmicsForm.doe"
        label="Are you submitting samples to a DOE user facility (JGI, EMSL)? *"
        @change="resetFields('doe')"
      >
        <v-radio
          label="No"
          :value="false"
          class="mb-2 mt-0"
        />
        <v-radio
          label="Yes"
          :value="true"
          class="mb-2 mt-0"
        />
      </v-radio-group>

      <v-radio-group
        v-if="multiOmicsForm.dataGenerated === false && multiOmicsForm.doe"
        v-model="multiOmicsForm.award"
        label="What kind of project have you been awarded? *"
        :rules="projectAwardValidationRules()"
        class="pb-5"
      >
        <div class="d-flex">
          <v-radio
            value="CSP"
            label="CSP"
          />
          <div class="ml-1">
            (<a
              href="https://jgi.doe.gov/user-programs/program-info/csp-overview/csp-annual-call/"
              target="_blank"
              rel="noopener noreferrer"
            >Community Science Program</a>)
          </div>
        </div>

        <div class="d-flex">
          <v-radio
            value="BERSS"
            label="BERSS"
          />
          <div class="ml-1">
            (<a
              href="https://jgi.doe.gov/user-programs/other-programs/"
              target="_blank"
              rel="noopener noreferrer"
            >Biological and Environmental Research Support Science</a>)
          </div>
        </div>

        <div class="d-flex">
          <v-radio
            value="BRCs"
            label="BRCs"
          />
          <div class="ml-1">
            (<a
              href="https://jgi.doe.gov/user-programs/other-programs/"
              target="_blank"
              rel="noopener noreferrer"
            >Bioenergy Research Centers</a>)
          </div>
        </div>

        <div class="d-flex">
          <v-radio
            value="FICUS"
            label="FICUS"
          />
          <div class="ml-1">
            (<a
              href="https://www.emsl.pnnl.gov/basic/ficus-program/1872"
              target="_blank"
              rel="noopener noreferrer"
            >Facilities Integrating Collaborations for User Science</a>)
          </div>
        </div>

        <div class="d-flex">
          <v-radio
            value="MONet"
            label="MONet"
          />
          <div class="ml-1">
            (<a
              href="https://www.emsl.pnnl.gov/monet"
              target="_blank"
              rel="noopener noreferrer"
            >Molecular Observation Network</a>)
          </div>
        </div>

        <v-radio
          :value="OTHER"
        >
          <template #label>
            <span class="mr-4">Other</span>
            <v-text-field
              v-model="multiOmicsForm.otherAward"
              class="pa-0 ma-0"
              dense
              hide-details="auto"
              outlined
              :rules="otherAwardValidationRules()"
            />
          </template>
        </v-radio>
      </v-radio-group>
      <div
        v-if="multiOmicsForm.dataGenerated === false && multiOmicsForm.doe"
        class="pb-4"
      >
        <DoeFacility
          @revalidate="revalidate"
        />
      </div>

      <v-alert
        v-if="templateChoiceDisabled"
        type="warning"
      >
        <p class="text-h5">
          Data type choice disabled
        </p>
        Data types cannot be changed when there are already metadata rows in step 6.  To change the template, return to step 6 and remove all data.
      </v-alert>

      <DataTypes
        v-if="multiOmicsForm.dataGenerated === false && multiOmicsForm.doe === false"
        legend="Which datatypes may be generated later?"
        :show-data-compatibility-questions="false"
        @revalidate="revalidate"
      />
      <DataTypes
        v-if="multiOmicsForm.facilityGenerated === false"
        legend="Which datatypes were generated?"
        :show-data-compatibility-questions="true"
        @revalidate="revalidate"
      />
      <div
        v-if="multiOmicsForm.facilities.includes('EMSL') || multiOmicsForm.facilities.includes('JGI')"
        class="d-flex flex-column grow my-4"
      >
        <v-text-field
          v-for="(awardDoi, i) in multiOmicsForm.awardDois"
          :key="`awardDoi${i}`"
          v-model="multiOmicsForm.awardDois[i]"
          label="Award DOI *"
          :hint="Definitions.doi"
          :rules="doiRequiredRules()"
          persistent-hint
          validate-on-blur
          outlined
          dense
          @change="revalidate"
        >
          <template #message="{ message }">
            <span v-html="message" />
          </template>
          <template #append-outer>
            <v-btn
              v-if="(multiOmicsForm.dataGenerated || multiOmicsForm.facilities.includes('EMSL') || multiOmicsForm.facilities.includes('JGI')) && multiOmicsForm.awardDois !== null"
              icon
              class="pb-2"
              :disabled="!(multiOmicsForm.facilities.length < multiOmicsForm.awardDois.length)"
              @click="removeAwardDoi(i)"
            >
              <v-icon>mdi-minus-circle</v-icon>
            </v-btn>
          </template>
        </v-text-field>

        <v-checkbox
          v-if="!multiOmicsForm.dataGenerated && (multiOmicsForm.facilities.includes('EMSL') || multiOmicsForm.facilities.includes('JGI'))"
          v-model="multiOmicsForm.unknownDoi"
          class="mt-0"
          :label="`I don't know my award DOI`"
          :hint="Definitions.unknownDoi"
          persistent-hint
          @change="revalidate"
        />
      </div>
      <v-btn
        v-if="multiOmicsForm.dataGenerated || multiOmicsForm.facilities.includes('EMSL') || multiOmicsForm.facilities.includes('JGI')"
        class="mb-4"
        depressed
        @click="addAwardDoi"
      >
        <v-icon class="pr-1">
          mdi-plus-circle
        </v-icon>
        Add Award DOI
      </v-btn>
    </v-form>
    <strong>* indicates required field</strong>
    <div class="d-flex mt-5">
      <v-btn
        color="gray"
        depressed
        :to="{ name: 'Study Form' }"
      >
        <v-icon class="pr-1">
          mdi-arrow-left-circle
        </v-icon>
        Go to previous step
      </v-btn>
      <v-spacer />
      <v-btn
        color="primary"
        depressed
        :disabled="(!multiOmicsFormValid)"
        :to="{ name: 'Environment Package' }"
      >
        Go to next step
        <v-icon class="pl-1">
          mdi-arrow-right-circle
        </v-icon>
      </v-btn>
    </div>
  </div>
</template>
