<script lang="ts">
import {
  defineComponent,
  ref,
  onMounted,
  watch,
  nextTick,
} from '@vue/composition-api';
// @ts-ignore
import NmdcSchema from 'nmdc-schema/nmdc_schema/nmdc_materialized_patterns.yaml';

import Definitions from '@/definitions';
import {
  multiOmicsForm, multiOmicsFormValid, multiOmicsAssociations, templateChoiceDisabled, contextForm, canEditSubmissionMetadata, AwardTypes,
} from '../store';
import SubmissionDocsLink from './SubmissionDocsLink.vue';
import SubmissionPermissionBanner from './SubmissionPermissionBanner.vue';

export default defineComponent({
  components: { SubmissionDocsLink, SubmissionPermissionBanner },
  setup() {
    const formRef = ref();

    function reValidate() {
      formRef.value.validate();
    }

    const facilityEnum = Object.keys(NmdcSchema.enums.ProcessingInstitutionEnum.permissible_values).filter(
      (facility: string) => ['EMSL', 'JGI'].includes(facility),
    );
    const projectAwardValidationRules = () => [(v: string) => {
      const awardTypes = Object.values(AwardTypes) as string[];
      const awardChosen = awardTypes.includes(v) || v === contextForm.otherAward;
      const valid = awardChosen || contextForm.facilities.length === 0;
      return valid || 'If submitting to a use facility, this field is required.';
    }];
    const otherAwardValidationRules = () => [(v: string) => {
      const awardTypes = Object.values(AwardTypes) as string[];
      if (contextForm.award && awardTypes.includes(contextForm.award)) {
        return true;
      }
      const inputEmpty = v.trim().length === 0;
      if (contextForm.facilities.length > 0) {
        return !inputEmpty || 'Please enter the kind of project award.';
      }
      return true;
    }];
    const doiRequiredRules = () => [(v: string) => {
      const valid = !!v || (!contextForm.facilityGenerated && contextForm.dataGenerated) || (contextForm.unknownDoi && !contextForm.dataGenerated);
      return valid || 'An award DOI is required if data was or is going to be generated by a DOE facility.';
    }];
    const revalidate = () => {
      nextTick(() => formRef.value.validate());
    };

    function addAwardDoi() {
      if (contextForm.awardDois === null || contextForm.awardDois.length === 0) {
        contextForm.awardDois = [''];
      } else {
        contextForm.awardDois.push('');
      }
    }

    function removeAwardDoi(i: number) {
      if (contextForm.awardDois === null) {
        contextForm.awardDois = [''];
      }
      if ((contextForm.facilities.length < contextForm.awardDois.length && !contextForm.dataGenerated) || (contextForm.facilityGenerated && contextForm.dataGenerated && contextForm.awardDois.length > 1) || (!contextForm.facilityGenerated && contextForm.dataGenerated)) {
        contextForm.awardDois.splice(i, 1);
      }
    }

    function facilityChange() {
      if (contextForm.awardDois === null || contextForm.awardDois.length < contextForm.facilities.length) {
        addAwardDoi();
      }
      revalidate();
    }

    function facilityGeneratedChange() {
      if (contextForm.facilityGenerated && (contextForm.awardDois === null || contextForm.awardDois.length < 1)) {
        addAwardDoi();
      }
      revalidate();
    }

    watch(
      () => contextForm.award,
      (award) => {
        const awardTypes = Object.values(AwardTypes) as string[];
        if (award && awardTypes.includes(award)) {
          contextForm.otherAward = '';
        }
        revalidate();
      },
    );

    onMounted(() => {
      formRef.value.validate();
    });

    return {
      facilityEnum,
      projectAwardValidationRules,
      otherAwardValidationRules,
      doiRequiredRules,
      revalidate,
      addAwardDoi,
      removeAwardDoi,
      facilityChange,
      facilityGeneratedChange,
      formRef,
      multiOmicsForm,
      multiOmicsAssociations,
      multiOmicsFormValid,
      Definitions,
      templateChoiceDisabled,
      contextForm,
      /* functions */
      reValidate,
      canEditSubmissionMetadata,
    };
  },
});
</script>

<template>
  <div>
    <div class="text-h2">
      Multi-omics Data
      <submission-docs-link anchor="multi-omics-data" />
    </div>
    <div class="text-h5">
      Information about the type of samples being submitted.
    </div>
    <submission-permission-banner
      v-if="!canEditSubmissionMetadata()"
    />
    <v-form
      ref="formRef"
      v-model="multiOmicsFormValid"
      class="my-6 mb-10"
      style="max-width: 1000px;"
      :disabled="!canEditSubmissionMetadata()"
    >
      <v-radio-group
        v-model="contextForm.dataGenerated"
        label="Have data already been generated for your study? *"
        :rules="[v => (v === true || v === false) || 'This field is required']"
        @change="revalidate"
      >
        <v-radio
          label="No"
          :value="false"
        />
        <v-radio
          label="Yes"
          :value="true"
        />
      </v-radio-group>
      <v-radio-group
        v-if="contextForm.dataGenerated"
        v-model="contextForm.facilityGenerated"
        label="Was data generated at a DOE user facility (JGI, EMSL)? *"
        :rules="[v => (v === true || v === false) || 'This field is required']"
        @change="facilityGeneratedChange"
      >
        <v-radio
          label="No"
          :value="false"
          hide-details
          class="mb-2 mt-0"
        />
        <v-radio
          label="Yes"
          :value="true"
          hide-details
          class="mb-2 mt-0"
        />
      </v-radio-group>
      <div
        v-if="contextForm.facilityGenerated"
      >
        <legend
          class="v-label theme--light mb-2"
          style="font-size: 14px;"
        >
          Which facility?
        </legend>
        <v-checkbox
          v-model="contextForm.facilities"
          label="EMSL"
          value="EMSL"
          hide-details
          class="mb-2 mt-0"
        />
        <v-checkbox
          v-model="contextForm.facilities"
          label="JGI"
          value="JGI"
          hide-details
          class="mb-2 mt-0"
        />
      </div>
      <v-radio-group
        v-if="contextForm.dataGenerated === false"
        v-model="contextForm.doe"
        label="Are you submitting samples to a DOE user facility (JGI, EMSL)? *"
        @change="reValidate"
      >
        <v-radio
          label="No"
          :value="false"
          class="mb-2 mt-0"
        />
        <v-radio
          label="Yes"
          :value="true"
          class="mb-2 mt-0"
        />
      </v-radio-group>
      <div
        v-if="contextForm.doe"
      >
        <legend
          class="v-label theme--light mb-2"
          style="font-size: 14px;"
        >
          Which facility?
        </legend>
        <v-checkbox
          v-model="contextForm.facilities"
          label="EMSL"
          value="EMSL"
          hide-details
          class="mb-2 mt-0"
        />
        <v-checkbox
          v-model="contextForm.facilities"
          label="JGI"
          value="JGI"
          hide-details
          class="mb-2 mt-0"
        />
      </div>

      <v-alert
        v-if="templateChoiceDisabled"
        type="warning"
      >
        <p class="text-h5">
          Data type choice disabled
        </p>
        Data types cannot be changed when there are already metadata rows in step 6.  To change the template, return to step 6 and remove all data.
      </v-alert>

      <!-- JGI -->
      <div v-if="contextForm.facilities.includes('JGI')">
        <div class="text-h6">
          Joint Genome Institute (JGI)
        </div>
        <v-checkbox
          v-model="multiOmicsForm.omicsProcessingTypes"
          label="Metagenome"
          value="mg-jgi"
          :disabled="templateChoiceDisabled"
          hide-details
        />
        <v-checkbox
          v-model="multiOmicsForm.omicsProcessingTypes"
          label="Metagenome (Long Read)"
          value="mg-lr-jgi"
          :disabled="templateChoiceDisabled"
          hide-details
        />
        <v-checkbox
          v-model="multiOmicsForm.omicsProcessingTypes"
          label="Metatranscriptome"
          value="mt-jgi"
          :disabled="templateChoiceDisabled"
          hide-details
        />
        <v-checkbox
          v-model="multiOmicsForm.omicsProcessingTypes"
          label="Metabolome"
          value="mb-jgi"
          disabled
          hide-details
        />
        <v-text-field
          v-if="multiOmicsForm.omicsProcessingTypes.some((v) => v.endsWith('jgi'))"
          v-model="multiOmicsForm.JGIStudyId"
          :rules="[
            v => !!v || 'JGI Proposal ID is required when processing was done at JGI' ,
            v => /^\d{6}$/.test(v) || 'JGI Proposal ID must be a 6 digit numerical value'
          ]"
          label="JGI Proposal ID *"
          hint="This is the 6 digit ID assigned to your JGI Proposal and is required when completing metadata for samples to be sent to JGI for sequencing."
          persistent-hint
          class="mt-4"
          outlined
          validate-on-blur
          dense
          :error-messages="multiOmicsForm.JGIStudyId ? undefined : ['JGI Proposal ID is required when processing was done at JGI']"
        />
      </div>

      <!-- EMSL -->
      <div v-if="contextForm.facilities.includes('EMSL')">
        <div class="text-h6 mt-4">
          Environmental Molecular Science Laboratory (EMSL)
        </div>
        <v-checkbox
          v-model="multiOmicsForm.omicsProcessingTypes"
          label="Metaproteome"
          value="mp-emsl"
          :disabled="templateChoiceDisabled"
          hide-details
        />
        <v-checkbox
          v-model="multiOmicsForm.omicsProcessingTypes"
          label="Metabolome"
          value="mb-emsl"
          :disabled="templateChoiceDisabled"
          hide-details
        />
        <v-checkbox
          v-model="multiOmicsForm.omicsProcessingTypes"
          label="Natural Organic Matter (FT-ICR MS)"
          value="nom-emsl"
          :disabled="templateChoiceDisabled"
          hide-details
        />
        <v-text-field
          v-if="multiOmicsForm.omicsProcessingTypes.some((v) => v.endsWith('emsl'))"
          v-model="multiOmicsForm.studyNumber"
          :rules="[
            v => !!v || 'EMSL Proposal ID is required when processing was done at EMSL',
            v => /^\d{5}$/.test(v) || 'EMSL Proposal ID must be a 5 digit numerical value'
          ]"
          hint="EMSL Proposal ID is required when processing was done at EMSL"
          persistent-hint
          label="EMSL Proposal ID *"
          class="mt-4"
          outlined
          validate-on-blur
          dense
          :error-messages="multiOmicsForm.studyNumber ? undefined : ['EMSL Proposal ID is required when processing was done at EMSL']"
        />
      </div>
      <!-- Other -->
      <div
        v-if="contextForm.facilityGenerated === false"
        class="text-h6 mt-4"
      >
        <legend
          class="v-label theme--light mb-2"
          style="font-size: 14px;"
        >
          Which datatypes were generated?
        </legend>
        <v-checkbox
          v-model="multiOmicsForm.omicsProcessingTypes"
          label="Metagenome"
          value="mg"
          :disabled="templateChoiceDisabled"
          hide-details
        />
        <div
          v-if="multiOmicsForm.omicsProcessingTypes.includes('mg')"
          class="v-label theme--light my-2 mx-8"
          style="font-size: 14px;"
        >
          NMDC currently supports external sequencing data that is comparable to data generated by the Joint Genome Institute (JGI):
          <ul
            class="my-2"
          >
            <li
              class="my-2"
            >
              Kapa Biosystems HyperPrep library preparation kit (Roche)
            </li>
            <li
              class="my-2"
            >
              Illumina NovaSeq X with a 2x150 run mode
            </li>
          </ul>
          Additional details about <a href="https://doi.org/10.1128/msystems.00804-20">metagenome processing</a> are available.
          If you have questions please contact <a href="mailto:support@microbiomedata.org">support@microbiomedata.org</a>
          <v-radio-group
            v-model="multiOmicsForm.mgCompatible"
            label="Is the generated data compatible? *"
          >
            <v-radio
              label="No"
              :value="false"
            />
            <v-radio
              label="Yes"
              :value="true"
            />
          </v-radio-group>
          <v-radio-group
            v-if="multiOmicsForm.mgCompatible"
            v-model="multiOmicsForm.mgInterleaved"
            label="Is the data in interleaved format? *"
          >
            <v-radio
              label="No"
              :value="false"
            />
            <v-radio
              label="Yes"
              :value="true"
            />
          </v-radio-group>
        </div>
        <v-checkbox
          v-model="multiOmicsForm.omicsProcessingTypes"
          label="Metatranscriptome"
          value="mt"
          :disabled="templateChoiceDisabled"
          hide-details
        />
        <div
          v-if="multiOmicsForm.omicsProcessingTypes.includes('mt')"
          class="v-label theme--light my-2 mx-8"
          style="font-size: 14px;"
        >
          NMDC currently supports external sequencing data that is comparable to data generated by the Joint Genome Institute (JGI):
          <ul
            class="my-2"
          >
            <li
              class="my-2"
            >
              Qiagen FastSelect 5S/16S/23s for bacterial rRNA depletion kit
            </li>
            <li
              class="my-2"
            >
              Illumina TruSeq Stranded Total RNA HT sample prep kit
            </li>
            <li
              class="my-2"
            >
              Illumina NovaSeq X with a 2x150 run mode
            </li>
          </ul>
          Additional details about <a href="https://jgi.doe.gov/wp-content/uploads/2022/03/20220125_metatranscriptome_planning_overview-FINAL.pdf">metatranscriptomes processing</a> are available.
          If you have questions please contact <a href="mailto:support@microbiomedata.org">support@microbiomedata.org</a>
          <v-radio-group
            v-model="multiOmicsForm.mtCompatible"
            label="Is the generated data compatible? *"
          >
            <v-radio
              label="No"
              :value="false"
            />
            <v-radio
              label="Yes"
              :value="true"
            />
          </v-radio-group>
          <v-radio-group
            v-if="multiOmicsForm.mtCompatible"
            v-model="multiOmicsForm.mtInterleaved"
            label="Is the dasta in interleaved format? *"
          >
            <v-radio
              label="No"
              :value="false"
            />
            <v-radio
              label="Yes"
              :value="true"
            />
          </v-radio-group>
        </div>

        <v-checkbox
          v-model="multiOmicsForm.omicsProcessingTypes"
          label="Metaproteome"
          value="mp"
          :disabled="templateChoiceDisabled"
          hide-details
        />
        <v-checkbox
          v-model="multiOmicsForm.omicsProcessingTypes"
          label="Metabolome"
          value="mb"
          :disabled="templateChoiceDisabled"
          hide-details
        />
        <v-checkbox
          v-model="multiOmicsForm.omicsProcessingTypes"
          label="Natural Organic Matter (FT-ICR MS)"
          value="nom"
          :disabled="templateChoiceDisabled"
          hide-details
        />
      </div>
    </v-form>
    <strong>* indicates required field</strong>
    <div class="d-flex mt-5">
      <v-btn
        color="gray"
        depressed
        :to="{ name: 'Study Form' }"
      >
        <v-icon class="pr-1">
          mdi-arrow-left-circle
        </v-icon>
        Go to previous step
      </v-btn>
      <v-spacer />
      <v-btn
        color="primary"
        depressed
        :disabled="(!multiOmicsFormValid)"
        :to="{ name: 'Environment Package' }"
      >
        Go to next step
        <v-icon class="pl-1">
          mdi-arrow-right-circle
        </v-icon>
      </v-btn>
    </div>
  </div>
</template>
