<script lang="ts">
import {
  defineComponent,
  onMounted,
  ref,
  watch,
  nextTick,
} from '@vue/composition-api';
import {
  contextForm,
  contextFormValid,
  addressForm,
  addressFormValid,
} from '../store';
import SubmissionContextShippingForm from './SubmissionContextShippingForm.vue';

export default defineComponent({
  components: { SubmissionContextShippingForm },
  setup() {
    const formRef = ref();
    const showAddressForm = ref(false);
    const addressFormRef = ref();
    const date = ref(null);
    const datePicker = ref(false);
    const address = ref({});
    const sampleItems = ref(['water_extract_soil']);
    const biosafetyLevels = ref(['BSL2']);
    const projectAwardValidationRules = () => [(v) => {
      const awardChosen = v === 'MONet' || v === 'FICUS' || v === contextForm.otherAward;
      const valid = awardChosen || contextForm.facilities.length === 0;
      return valid || 'If submitting to a user facility, an award is required.';
    }];

    watch(
      () => contextForm.facilities,
      () => {
        nextTick(() => formRef.value.validate());
      },
      { deep: true },
    );

    onMounted(() => {
      formRef.value.validate();
    });

    return {
      formRef,
      contextForm,
      contextFormValid,
      addressForm,
      addressFormValid,
      showAddressForm,
      addressFormRef,
      address,
      date,
      datePicker,
      sampleItems,
      biosafetyLevels,
      projectAwardValidationRules,
    };
  },
});
</script>

<template>
  <div>
    <div class="text-h2">
      Submission Context
    </div>
    <div class="text-h5">
      Provide context about what your submission is.
    </div>
    <v-form
      ref="formRef"
      v-model="contextFormValid"
      class="mb-2"
      style="max-width: 1000px;"
    >
      <v-radio-group
        v-model="contextForm.dataGenerated"
        label="Has data already been generated for your study?*"
        :rules="[v => (v === true || v === false) || 'This field is required']"
      >
        <v-radio
          label="No"
          :value="false"
        />
        <v-radio
          label="Yes"
          :value="true"
        />
      </v-radio-group>
      <v-checkbox
        v-if="contextForm.dataGenerated"
        v-model="contextForm.facilityGenerated"
        label="Data was generated by a DOE user facility"
        hide-details
        class="mb-2 mt-0"
      />
      <div v-if="contextForm.dataGenerated === false">
        <legend
          class="v-label theme--light mb-2"
          style="font-size: 14px;"
        >
          Are you submitting metadata for samples that will be sent to a DOE user factility?
        </legend>
        <v-checkbox
          v-model="contextForm.facilities"
          label="EMSL"
          value="EMSL"
          hide-details
        />
        <v-checkbox
          v-model="contextForm.facilities"
          label="JGI"
          value="JGI"
          hide-details
        />
        <submission-context-shipping-form
          v-if="contextForm.dataGenerated === false && contextForm.facilities.includes('EMSL')"
        />
        <v-radio-group
          v-if="contextForm.dataGenerated === false && contextForm.facilities.length > 0"
          v-model="contextForm.award"
          label="What kind of project have you been awarded?"
          :rules="projectAwardValidationRules()"
        >
          <v-radio
            label="FICUS"
            value="FICUS"
          />
          <v-radio
            label="MONet"
            value="MONet"
          />
          <v-radio
            :value="contextForm.otherAward"
          >
            <template #label>
              <span class="mr-4">Other</span>
              <v-text-field
                v-model="contextForm.otherAward"
                class="pa-0 ma-0"
                dense
                hide-details
                outlined
              />
            </template>
          </v-radio>
        </v-radio-group>
      </div>
    </v-form>
    <strong>* indicates required field</strong>
    <div class="d-flex">
      <v-spacer />
      <v-btn
        color="gray"
        depressed
        :to="{ name: 'Study Form' }"
        :disabled="!contextFormValid"
      >
        Go to next step
        <v-icon class="pl-1">
          mdi-arrow-right-circle
        </v-icon>
      </v-btn>
    </div>
  </div>
</template>
