<script lang="ts">
import {
  defineComponent,
  ref,
  onMounted,
  watch,
  nextTick,
} from '@vue/composition-api';
import NmdcSchema from 'nmdc-schema/jsonschema/nmdc.schema.json';
import Definitions from '@/definitions';
import {
  contextForm,
  contextFormValid,
  AwardTypes,
} from '../store';
import SubmissionContextShippingForm from './SubmissionContextShippingForm.vue';

export default defineComponent({
  components: { SubmissionContextShippingForm },
  setup() {
    const formRef = ref();
    const facilityEnum = NmdcSchema.$defs.ProcessingInstitutionEnum.enum.filter(
      (facility: string) => ['EMSL', 'JGI'].includes(facility),
    );
    const projectAwardValidationRules = () => [(v: string) => {
      const awardChosen = v === 'MONet' || v === 'FICUS' || v === contextForm.otherAward;
      const valid = awardChosen || contextForm.facilities.length === 0;
      return valid || 'If submitting to a use facility, this field is required.';
    }];
    const otherAwardValidationRules = () => [(v: string) => {
      const awardTypes = Object.values(AwardTypes) as string[];
      if (contextForm.award && awardTypes.includes(contextForm.award)) {
        return true;
      }
      const inputEmpty = v.trim().length === 0;
      if (contextForm.facilities.length > 0) {
        return !inputEmpty || 'Please enter the kind of project award.';
      }
      return true;
    }];
    const doiRequiredRules = () => [(v: string) => {
      const valid = !!v || !contextForm.facilityGenerated;
      return valid || 'Award DOI associated with DOE user facility project';
    }];
    const revalidate = () => {
      nextTick(() => formRef.value.validate());
    };

    watch(
      () => contextForm.award,
      (award) => {
        const awardTypes = Object.values(AwardTypes) as string[];
        if (award && awardTypes.includes(award)) {
          contextForm.otherAward = '';
        }
        revalidate();
      },
    );

    onMounted(() => {
      formRef.value.validate();
    });

    return {
      Definitions,
      facilityEnum,
      formRef,
      contextForm,
      contextFormValid,
      projectAwardValidationRules,
      otherAwardValidationRules,
      doiRequiredRules,
      revalidate,
    };
  },
});
</script>

<template>
  <div>
    <div class="text-h2">
      Submission Context
    </div>
    <div class="text-h5">
      Data and sample status
    </div>
    <v-form
      ref="formRef"
      v-model="contextFormValid"
      style="max-width: 1000px;"
      class="mb-2"
    >
      <v-radio-group
        v-model="contextForm.dataGenerated"
        label="Has data already been generated for your study? *"
        :rules="[v => (v === true || v === false) || 'This field is required']"
        @change="revalidate"
      >
        <v-radio
          label="No"
          :value="false"
        />
        <v-radio
          label="Yes"
          :value="true"
        />
      </v-radio-group>
      <v-checkbox
        v-if="contextForm.dataGenerated"
        v-model="contextForm.facilityGenerated"
        label="Data was generated by a DOE user facility"
        hide-details
        class="mb-2 mt-0"
        @change="revalidate"
      />
      <v-text-field
        v-if="contextForm.dataGenerated"
        v-model="contextForm.datasetDoi"
        :label="`Dataset DOI ${contextForm.facilityGenerated ? '*' : ''}`"
        :hint="Definitions.doi"
        :rules="doiRequiredRules()"
        persistent-hint
        validate-on-blur
        outlined
        dense
        @change="revalidate"
      />
      <div v-if="contextForm.dataGenerated === false">
        <legend
          class="v-label theme--light mb-2"
          style="font-size: 14px;"
        >
          Are you submitting metadata for samples that will be sent to a DOE user facility?
        </legend>
        <v-checkbox
          v-for="facility in facilityEnum"
          :key="facility"
          v-model="contextForm.facilities"
          :label="facility"
          :value="facility"
          hide-details
          @change="revalidate"
        />
        <submission-context-shipping-form
          v-if="contextForm.dataGenerated === false && contextForm.facilities.includes('EMSL')"
        />
        <v-radio-group
          v-if="contextForm.dataGenerated === false && contextForm.facilities.length > 0"
          v-model="contextForm.award"
          label="What kind of project have you been awarded? *"
          :rules="projectAwardValidationRules()"
        >
          <v-radio
            label="FICUS"
            value="FICUS"
          />
          <v-radio
            label="MONet"
            value="MONet"
          />
          <v-radio
            :value="contextForm.otherAward"
          >
            <template #label>
              <span class="mr-4">Other</span>
              <v-text-field
                v-model="contextForm.otherAward"
                class="pa-0 ma-0"
                dense
                hide-details
                outlined
                :rules="otherAwardValidationRules()"
              />
            </template>
          </v-radio>
        </v-radio-group>
      </div>
    </v-form>
    <strong>* indicates required field</strong>
    <div class="d-flex">
      <v-spacer />
      <v-btn
        color="gray"
        depressed
        :to="{ name: 'Study Form' }"
        :disabled="!contextFormValid"
      >
        Go to next step
        <v-icon class="pl-1">
          mdi-arrow-right-circle
        </v-icon>
      </v-btn>
    </div>
  </div>
</template>
