version: "3.3"
services:
  db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .docker-env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  backend:
    depends_on:
      - db
    env_file:
      - .docker-env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - public
      - default
    ports:
      - "8000:8000"

  web:
    depends_on: 
      - backend
    env_file:
      - .docker-env
    environment:
      BACKEND_URL: "http://backend:8000"
      DNS_ADDRESS: "127.0.0.11"
    build:
      context: web/
      dockerfile: Dockerfile
    networks:
      - public
      - default
    ports:
      - "8080:80"

volumes:
  app-db-data:

networks:
  public:
