FROM python:3.12-slim
LABEL org.opencontainers.image.source=https://github.com/microbiomedata/nmdc-server

RUN apt-get update && apt-get install -y postgresql-client git libpq-dev libc6-dev gcc

RUN pip install -U pip setuptools wheel
COPY pyproject.toml /app/
RUN --mount=source=.git,target=/app/.git,type=bind pip install -e /app

COPY nmdc_server /app/nmdc_server
COPY .env.production /app/.env

WORKDIR /app/
CMD ["celery", "-b", "redis://redis:6379/0", "--result-backend", "redis://redis:6379/0", "-A", "nmdc_server.celery_config.celery_app", "worker", "-E", "-l", "INFO"]
