version: "3.3"
services:
  redis:
    image: redis

  data:
    image: nginx

  db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    env_file:
      - .docker-env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=nmdc

  worker:
    image: ghcr.io/microbiomedata/nmdc-server/worker:latest
    depends_on:
      - redis
      - db
    env_file:
      - .docker-env
      - .env
    build:
      context: .
      dockerfile: Dockerfile.worker

  backend:
    image: ghcr.io/microbiomedata/nmdc-server/server:latest
    depends_on:
      - db
      - redis
    env_file:
      - .docker-env
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PGHOST=db
    networks:
      - public
      - default
    ports:
      - "8000:8000"

  web:
    image: ghcr.io/microbiomedata/nmdc-server/client:latest
    depends_on:
      - backend
      - data
    env_file:
      - .docker-env
    environment:
      BACKEND_URL: "http://backend:8000"
      DNS_ADDRESS: "127.0.0.11"
    build:
      context: web/
      dockerfile: Dockerfile
    networks:
      - public
      - default
    ports:
      - "8080:80"

volumes:
  app-db-data:
  app-db-ingest:

networks:
  public:
