/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AmpliconObjectDataTable: typeof import('./components/AmpliconObjectDataTable.vue')['default']
    AppBanner: typeof import('./components/AppBanner.vue')['default']
    AppHeader: typeof import('./components/Presentation/AppHeader.vue')['default']
    AttributeItem: typeof import('./components/Presentation/AttributeItem.vue')['default']
    AttributeList: typeof import('./components/Presentation/AttributeList.vue')['default']
    AuthButton: typeof import('./components/Presentation/AuthButton.vue')['default']
    BinnedSummaryWrapper: typeof import('./components/Wrappers/BinnedSummaryWrapper.vue')['default']
    BulkDownload: typeof import('./components/BulkDownload.vue')['default']
    ChartContainer: typeof import('./components/Presentation/ChartContainer.vue')['default']
    ClusterMap: typeof import('./components/ClusterMap.vue')['default']
    ConditionChips: typeof import('./components/Presentation/ConditionChips.vue')['default']
    DataObjectTable: typeof import('./components/DataObjectTable.vue')['default']
    DateHistogram: typeof import('./components/Presentation/DateHistogram.vue')['default']
    DateInput: typeof import('./components/Presentation/DateInput.vue')['default']
    DownloadDialog: typeof import('./components/DownloadDialog.vue')['default']
    EcosystemSankey: typeof import('./components/EcosystemSankey.vue')['default']
    FacetBarChart: typeof import('./components/Presentation/FacetBarChart.vue')['default']
    FacetedSearch: typeof import('./components/FacetedSearch.vue')['default']
    FacetSummaryWrapper: typeof import('./components/Wrappers/FacetSummaryWrapper.vue')['default']
    FilterDate: typeof import('./components/Presentation/FilterDate.vue')['default']
    FilterFloat: typeof import('./components/Presentation/FilterFloat.vue')['default']
    FilterGene: typeof import('./components/FilterGene.vue')['default']
    FilterList: typeof import('./components/Presentation/FilterList.vue')['default']
    FilterSankeyTree: typeof import('./components/FilterSankeyTree.vue')['default']
    FilterTree: typeof import('./components/FilterTree.vue')['default']
    MenuContent: typeof import('./components/MenuContent.vue')['default']
    OrcidId: typeof import('./components/Presentation/OrcidId.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SampleListExpansion: typeof import('./components/SampleListExpansion.vue')['default']
    SearchResults: typeof import('./components/Presentation/SearchResults.vue')['default']
    TeamInfo: typeof import('./components/TeamInfo.vue')['default']
    TimeHistogram: typeof import('./components/Presentation/TimeHistogram.vue')['default']
    TooltipCard: typeof import('./components/TooltipCard.vue')['default']
    UpSet: typeof import('./components/Presentation/UpSet.vue')['default']
    UserEmailModal: typeof import('./components/UserEmailModal.vue')['default']
  }
}
