name: deploy

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  # We don't want to do certain steps if this is running in a fork
  IS_ORIGINAL_REPO: ${{ github.repository == 'microbiomedata/nmdc-server' }}

  # Used to determine if we add the special `prod` Docker image tag
  IS_PROD_RELEASE: ${{ startsWith(github.ref, 'refs/tags/v') }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: [server, client, worker]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # history for all branches and tags is needed for setuptools-scm
          fetch-depth: 0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/microbiomedata/nmdc-server/${{ matrix.image }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=raw,value=prod,enable=${{ env.IS_PROD_RELEASE }}      

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.image == 'client' && 'web' || '.' }}
          push: ${{ env.IS_ORIGINAL_REPO }}
          file: ${{ matrix.image == 'worker' && 'Dockerfile.worker' || (matrix.image == 'client' && 'web/Dockerfile' || 'Dockerfile') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  redeploy:
    needs: build

    runs-on: ubuntu-latest

    env:
      WORKLOAD_API_BASE: https://rancher2.spin.nersc.gov/v3/project/c-tmq7p:p-bkv45/workloads

    strategy:
      matrix:
        deployment: [ backend, frontend, worker ]

    steps:
      - name: Redeploy nmdc-dev:portal-${{ matrix.deployment }}
        if: ${{ env.IS_PROD_RELEASE == 'false' && env.IS_ORIGINAL_REPO == 'true' }}
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ env.WORKLOAD_API_BASE }}/deployment:nmdc-dev:portal-${{ matrix.deployment }}?action=redeploy
          method: POST
          username: ${{ secrets.SPIN_USER }}
          password: ${{ secrets.SPIN_PASSWORD }}

      - name: Redeploy nmdc:${{ matrix.deployment }}
        if: ${{ env.IS_PROD_RELEASE == 'true' && env.IS_ORIGINAL_REPO == 'true' }}
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ env.WORKLOAD_API_BASE }}/deployment:nmdc:${{ matrix.deployment }}?action=redeploy
          method: POST
          username: ${{ secrets.SPIN_USER }}
          password: ${{ secrets.SPIN_PASSWORD }}

      - name: Redeploy nmdc-sandbox:${{ matrix.deployment }}
        if: ${{ env.IS_PROD_RELEASE == 'true' && env.IS_ORIGINAL_REPO == 'true' }}
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ env.WORKLOAD_API_BASE }}/deployment:nmdc-sandbox:${{ matrix.deployment }}?action=redeploy
          method: POST
          username: ${{ secrets.SPIN_USER }}
          password: ${{ secrets.SPIN_PASSWORD }}