name: deploy

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
#
# SERVER
#
      -
        name: Build and push server
        uses: docker/build-push-action@v2
        with:
          tags: kitware/nmdc-server:latest
      # -
      #   name: Deploy server
      #   uses: fjogeleit/http-request-action@v1.3.3
      #   with:
      #     url: 'https://rancher2.spin.nersc.gov/v3/project/c-fwj56:p-nlxq2/workloads/deployment:nmdc-dev:backend?action=redeploy'
      #     method: 'POST'
      #     username: ${{ secrets.SPIN_USER }}
      #     password: ${{ secrets.SPIN_PASSWORD }}
#
# CLIENT
#
      -
        name: Build and push client
        uses: docker/build-push-action@v2
        with:
          tags: kitware/nmdc-client:latest
          context: web
      # -
      #   name: Deploy client
      #   uses: fjogeleit/http-request-action@v1.3.3
      #   with:
      #     url: 'https://rancher2.spin.nersc.gov/v3/project/c-fwj56:p-nlxq2/workloads/deployment:nmdc-dev:frontend?action=redeploy'
      #     method: 'POST'
      #     username: ${{ secrets.SPIN_USER }}
      #     password: ${{ secrets.SPIN_PASSWORD }}
#
# WORKER
#
      -
        name: Build and push worker
        uses: docker/build-push-action@v2
        with:
          tags: kitware/nmdc-worker:latest
          file: ./Dockerfile.worker
      # - 
      #   name: Deploy worker
      #   uses: fjogeleit/http-request-action@v1.3.3
      #   with:
      #     url: 'https://rancher2.spin.nersc.gov/v3/project/c-fwj56:p-nlxq2/workloads/deployment:nmdc-dev:worker?action=redeploy'
      #     method: 'POST'
      #     username: ${{ secrets.SPIN_USER }}
      #     password: ${{ secrets.SPIN_PASSWORD }}
