name: dockerhub

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [server, client]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push server
        uses: docker/build-push-action@v1
        if: ${{ matrix.image == 'server' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: jbeezley/nmdc-server
          tags: latest

      - name: Build and push client
        uses: docker/build-push-action@v1
        if: ${{ matrix.image == 'client' }}
        env:
          VUE_APP_BASE_URL: http://backend.jbeezley.development.svc.spin.nersc.org/api
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: jbeezley/nmdc-client
          tags: latest
          path: web
